{
  description = "Python + R project environment";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs =
    { nixpkgs, ... }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs {
        inherit system;
        config.allowUnfree = true;
      };

      rPackages = with pkgs.rPackages; [
        # Language support
        languageserver

        # Data read write
        here
        arrow
        haven
        readxl
        writexl
        foreign
        janitor

        # Tidyverse
        tidyverse
        tidylog

        # Graphics
        ggplot2
        cowplot
        ggthemes
        ggfixest
        scales

        # Faster tools
        collapse

        # Inference
        fixest
        MatchIt

        # Geospatial tools
        sf
        ggspatial

        # Data download
        fredr

      ];

      rWrapped = pkgs.rWrapper.override {
        packages = rPackages;
      };
      rProfile =
        pkgs.runCommand "r-project-profile.R"
          {
            buildInputs = [ pkgs.R ] ++ rWrapped.recommendedPackages ++ rPackages;
          }
          ''
            echo "# Autogenerated from the Nix project R environment." > "$out"
            echo -n ".libPaths(c(.libPaths(), \"" >> "$out"
            echo -n "$R_LIBS_SITE" | sed -e 's/:/", "/g' >> "$out"
            echo -n "\"))" >> "$out"
            echo >> "$out"
          '';
      rHome = "${pkgs.R}/lib/R";

      r = pkgs.writeShellScriptBin "R" ''
        # Shell wrapper for R executable.
        R_HOME_DIR="${rHome}"
        if test "''${R_HOME_DIR}" = "${rHome}"; then
          :
        fi
        exec ${rWrapped}/bin/R "$@"
      '';

      nativeLibraries = with pkgs; [
        # Required C libraries for uv-downloaded wheels.
        expat
        zlib
        stdenv.cc.cc.lib
      ];
    in
    {
      devShells.${system}.default = pkgs.mkShell {
        packages =
          with pkgs;
          [
            # R environment
            r

            # Python environment
            uv
            python3
          ]
          ++ nativeLibraries;

        LD_LIBRARY_PATH = "${pkgs.lib.makeLibraryPath nativeLibraries}:/run/opengl-driver/lib";
        R_PROFILE = rProfile;
        UV_PROJECT_ENVIRONMENT = ".venv-nixos";
      };
    };
}
