# Generated by code/split_do_r_scripts.py.
# Edit the source Do script or split specification, then regenerate.
# Source: Do/H2A Clean and Load.R lines 420-754
# Source SHA256: 07cc96d911887417cee0e9ec6a6a2f99263553a32a69f57ea57f687287ad3824

if (!exists("path_processed", mode = "function")) {
  local({
    split_current_file <- function() {
      frames <- sys.frames()
      for (idx in rev(seq_along(frames))) {
        ofile <- frames[[idx]]$ofile
        if (!is.null(ofile)) {
          return(normalizePath(ofile, winslash = "/", mustWork = FALSE))
        }
      }

      file_arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)
      if (length(file_arg) > 0) {
        return(normalizePath(sub("^--file=", "", file_arg[[1]]), winslash = "/", mustWork = FALSE))
      }

      normalizePath(getwd(), winslash = "/", mustWork = FALSE)
    }

    source(file.path(dirname(split_current_file()), "c00_setup.R"))
  })
}

## _____________________________________________________________________________
## Year by Year version --------------------------------------------------------
## _____________________________________________________________________________

## Fips Codes ------------------------------------------

fips_codes <- read_csv(
  file = path_raw("geographic_crosswalks", "phil", "fips_codes.csv")
)
fips_codes <- fips_codes %>%
  mutate(fips = split_fips2(fips))

## AEWR Regions ----------------------------------------

aewr_regions <- read_csv(
  file = path_raw("geographic_crosswalks", "phil", "aewr_regions.csv")
)

## PPI --------------------------------------------------
# Source: https://fred.stlouisfed.org/series/WPU01

ppi_data <- read_parquet(path_processed("ppi_2012.parquet"))

## County Boundary ------------------------------------

# cleaned in the original stata file
state_border_pairs <- read_csv(
  file = path_raw("geographic_crosswalks", "state_border_pairs.csv")
)
border_counties_allmatches <- read_csv(
  file = path_raw("geographic_crosswalks", "border_counties_allmatches.csv")
)

full_county_set <- read_parquet(path_int("county_adjacency2010.parquet"))

dim(state_border_pairs)
dim(border_counties_allmatches)
dim(full_county_set)

## Census of Agriculture ------------------------------

options(arrow.skip_nul = TRUE)
census_of_agriculture <- read_parquet(path_int(
  "qs_census_selected_obs.parquet"
))

# general cleaning #

head(census_of_agriculture)

ag_census_data_items <- census_of_agriculture %>%
  group_by(commodity_desc) %>%
  tally()

# want: FARM OPERATIONS, AG LAND

census_of_agriculture_trim <- census_of_agriculture %>%
  filter(commodity_desc == "FARM OPERATIONS" | commodity_desc == "AG LAND")

census_of_agriculture_trim_items <- census_of_agriculture_trim %>%
  group_by(short_desc) %>%
  tally()

census_of_agriculture_trim <- census_of_agriculture_trim %>%
  filter(short_desc == "AG LAND, CROPLAND - ACRES")

# fix fips

census_of_agriculture_trim <- census_of_agriculture_trim %>%
  mutate(
    countyfips = split_countyfips(state_fips_code, county_code)
  )

census_of_agriculture_trim <- census_of_agriculture_trim %>%
  arrange(countyfips, year)

census_of_agriculture_trim <- census_of_agriculture_trim %>%
  mutate(label = "cropland_acr") %>%
  select(year, countyfips, value, label)

census_of_agriculture_trim <- census_of_agriculture_trim %>%
  filter(!is.na(countyfips))

census_of_agriculture_cropland <- census_of_agriculture_trim %>%
  pivot_wider(names_from = "label", values_from = "value")

head(census_of_agriculture_trim)

census_of_agriculture_cropland %>%
  write_parquet(path_processed("census_ag_cropland_year.parquet"))

rm(census_of_agriculture_trim)

census_of_agriculture_cropland_base <- census_of_agriculture_cropland %>%
  filter(year == 2007) %>%
  rename(cropland_acr_2007 = cropland_acr) %>%
  select(-year)

census_of_agriculture_cropland_base %>%
  write_parquet(path_processed("census_ag_cropland_2007_year.parquet"))

rm(census_of_agriculture_cropland_base)

## H2A Data -------------------------------------------

h2a_data <- read_parquet(
  path_int("h2a_aggregated.parquet"),
  stringsAsFactors = F
)

head(h2a_data)

# fix fips code

h2a_data <- h2a_data %>%
  mutate(
    cnty_fips_string = str_pad(
      as.character(county_fips_code),
      width = 3,
      side = "left",
      pad = "0"
    ),
    st_fips_string = str_pad(
      as.character(state_fips_code),
      width = 2,
      side = "left",
      pad = "0"
    )
  )

h2a_data <- h2a_data %>%
  mutate(countyfips = split_fips5(paste0(st_fips_string, cnty_fips_string)))


# clean by dropping old codes #

h2a_data <- h2a_data %>%
  filter(year <= 2022 & year > 2007 & !is.na(county_fips_code)) %>%
  select(
    -cnty_fips_string,
    -st_fips_string,
    -state_fips_code,
    -county_fips_code
  )

# collapse by period, county (county and state fips)

## Handle NAs?

head(h2a_data)

write_parquet(h2a_data, path_processed("h2a_data_year.parquet"))
cat("h2a_data_year:", nrow(h2a_data), "rows,", ncol(h2a_data), "cols\n")

## AEWR -------------------------------------------------

aewr_data <- read_parquet(
  path_int("aewr.parquet"),
  stringsAsFactors = F
)

aewr_data <- merge(
  x = aewr_data,
  y = ppi_data,
  by = "year",
  all.x = T,
  all.y = F
)

aewr_data <- aewr_data %>%
  mutate(
    aewr = as.numeric(aewr),
    state_fips_code = split_fips2(state_fips_code)
  ) %>%
  mutate(aewr_ppi = aewr / ppi_2012)

aewr_data <- aewr_data %>%
  arrange(state_fips_code, year) %>%
  group_by(state_fips_code) %>%
  mutate(
    aewr_ppi_l1 = lag(aewr_ppi, n = 1, order_by = state_fips_code),
    aewr_l1 = lag(aewr, n = 1, order_by = state_fips_code),
    aewr_ppi_l2 = lag(aewr_ppi, n = 2, order_by = state_fips_code),
    aewr_l2 = lag(aewr, n = 2, order_by = state_fips_code)
  )

aewr_data <- aewr_data %>%
  filter(year > 2007 & year <= 2022)

aewr_data <- merge(
  x = aewr_data,
  y = fips_codes,
  by.x = "state_fips_code",
  by.y = "fips",
  all.x = T,
  all.y = F
)

aewr_data <- aewr_data %>%
  select(
    aewr,
    aewr_ppi,
    aewr_l1,
    aewr_ppi_l1,
    aewr_l2,
    aewr_ppi_l2,
    year,
    state_abbrev
  )

head(aewr_data)

write_parquet(aewr_data, path_processed("aewr_data_year.parquet"))
cat("aewr_data_year:", nrow(aewr_data), "rows,", ncol(aewr_data), "cols\n")

# full for TS

aewr_data <- read_parquet(
  path_int("aewr.parquet"),
  stringsAsFactors = F
) %>%
  mutate(aewr = as.numeric(aewr)) %>%
  mutate(year = as.numeric(year)) %>%
  mutate(state_fips_code = split_fips2(state_fips_code))

aewr_data <- aewr_data %>%
  arrange(state_fips_code, year)

aewr_data %>% group_by(year) %>% tally()

aewr_data <- merge(
  x = aewr_data,
  y = ppi_data,
  by = "year",
  all.x = T,
  all.y = F
)

aewr_data <- aewr_data %>%
  mutate(aewr_ppi = aewr / ppi_2012)

aewr_data <- merge(
  x = aewr_data,
  y = fips_codes,
  by.x = "state_fips_code",
  by.y = "fips",
  all.x = T,
  all.y = F
)

head(aewr_data)

# collapse by regions

aewr_data <- merge(
  x = aewr_data,
  y = aewr_regions,
  by = "state_abbrev",
  all.x = T
)

aewr_data <- aewr_data %>%
  group_by(aewr_region_num, year) %>%
  summarise(aewr = mean(aewr, na.rm = T), aewr_ppi = mean(aewr_ppi, na.rm = T))

head(aewr_data)

# make TS variables #
aewr_data <- aewr_data %>%
  arrange(aewr_region_num, year) %>%
  group_by(aewr_region_num) %>%
  mutate(
    aewr_ppi_l1 = lag(aewr_ppi, n = 1, order_by = aewr_region_num),
    aewr_l1 = lag(aewr, n = 1, order_by = aewr_region_num),
    aewr_ppi_l2 = lag(aewr_ppi, n = 2, order_by = aewr_region_num),
    aewr_l2 = lag(aewr, n = 2, order_by = aewr_region_num)
  )

aewr_data <- aewr_data %>%
  arrange(aewr_region_num, year) %>%
  mutate(
    ch_aewr = aewr - aewr_l1,
    ch_aewr_ppi = aewr_ppi - aewr_ppi_l1,
    pch_aewr = (aewr - aewr_l1) / aewr_l1,
    pch_aewr_ppi = (aewr_ppi - aewr_ppi_l1) / aewr_ppi_l1
  )

head(aewr_data)

aewr_data <- aewr_data %>%
  filter(!is.na(aewr_region_num))

# leav one out averages

loo_averages <- NULL

for (i in 1:17) {
  temp <- aewr_data %>%
    filter(aewr_region_num != i) %>% # leave one out, so not the one we want
    group_by(year) %>%
    summarise(
      loo_aewr = mean(aewr, na.rm = T),
      loo_aewr_ppi = mean(aewr_ppi, na.rm = T),
      aewr_region_num = i
    )
  loo_averages <- bind_rows(loo_averages, temp)
  rm(temp)
}

aewr_data <- merge(
  x = aewr_data,
  y = loo_averages,
  by = c("year", "aewr_region_num"),
  all.x = T
)

aewr_data <- aewr_data %>%
  arrange(year, aewr_region_num) %>%
  mutate(
    aewr_diff = aewr - loo_aewr,
    aewr_ppi_diff = aewr_ppi - loo_aewr_ppi,
    ln_aewr = log(aewr),
    ln_aewr_l1 = log(aewr / aewr_l1)
  )

head(aewr_data)

write_parquet(aewr_data, path_processed("aewr_data_full.parquet"))
cat("aewr_data_full:", nrow(aewr_data), "rows,", ncol(aewr_data), "cols\n")

