# Generated by code/split_do_r_scripts.py.
# Edit the source Do script or split specification, then regenerate.
# Source: Do/H2A Clean and Load.R lines 1-199
# Source SHA256: a32c63f5bd5343db2ca703ce8024bce608dd126cd2d3f7ba2baacfa3149da191

if (!exists("path_processed", mode = "function")) {
  local({
    split_current_file <- function() {
      frames <- sys.frames()
      for (idx in rev(seq_along(frames))) {
        ofile <- frames[[idx]]$ofile
        if (!is.null(ofile)) {
          return(normalizePath(ofile, winslash = "/", mustWork = FALSE))
        }
      }

      file_arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)
      if (length(file_arg) > 0) {
        return(normalizePath(sub("^--file=", "", file_arg[[1]]), winslash = "/", mustWork = FALSE))
      }

      normalizePath(getwd(), winslash = "/", mustWork = FALSE)
    }

    source(file.path(dirname(split_current_file()), "c00_setup.R"))
  })
}

ensure_project_dirs()
library(tidyverse)
library(arrow)
library(tidylog, warn.conflicts = FALSE)
## H2A: Load and clean datasets
## Phil Hoxie
## 1/11/24

## New Price Data (20260417) ----------------------

price_data <- read_parquet(path_int(
  "price_index_fisher_county_year.parquet"
)) %>%
  mutate(
    countyfips = as.numeric(fips),
    year = as.integer(year)
  ) %>%
  select(countyfips, year, fisher_index) %>%
  filter(year >= 2008 & year <= 2022)

write_parquet(
  price_data,
  path_processed("nass_fisher_price_index.parquet")
)
head(price_data)
rm(price_data)

## requires running master file first ##

## Two datasets, one by census period and one by year (calendar year)

## CZ wage quantile ------------------------------------

cz_wage_quantiles <- read_parquet(path_int("acs_czone_wage_quantiles.parquet"))

## state min wages ------------------------------------

state_minwages <- read_parquet(path_processed("fred_state_minwages.parquet"))

## Alt Min Wage from Ken -------------------------------

state_min_alt <- read_parquet(path_int("state_year_min_wage.parquet"))

## Fips Codes ------------------------------------------

fips_codes <- read_csv(
  file = path_raw("geographic_crosswalks", "phil", "fips_codes.csv")
)

## AEWR Regions ----------------------------------------

aewr_regions <- read_csv(
  file = path_raw("geographic_crosswalks", "phil", "aewr_regions.csv")
)

## Commuting Zones --------------------------------------

# source: https://sites.psu.edu/psucz/data/

cz_file <- read_csv(
  file = path_raw("geographic_crosswalks", "penn", "counties10-zqvz0r.csv")
)

cz_file <- cz_file %>%
  rename(countyfips = FIPS, cz_out10 = OUT10)

cz_integer_vars <- c(
  "countyfips",
  "cz_out10",
  "REP10",
  "Pop10",
  "Wage2010",
  "Wage2011",
  "Wage2012",
  "Wage2013",
  "Wage2014",
  "Wage2015",
  "CBSA10",
  "PEA10",
  "BEA2004",
  "TPMetro",
  "TPMicro",
  "TPcombined"
)
cz_file <- cz_file %>%
  mutate(across(all_of(cz_integer_vars), as.integer))

write_parquet(cz_file, path_processed("cz_file_2010.parquet"))


cz_file_small <- cz_file %>%
  select(countyfips, cz_out10)

write_parquet(cz_file_small, path_processed("cz_file_2010_small.parquet"))


## PPI --------------------------------------------------
# Source: https://fred.stlouisfed.org/series/WPU01

ppi_data <- read_csv(
  file = path_raw("fred", "WPU01.csv")
)

# average by year

ppi_data <- ppi_data %>%
  mutate(year = as.numeric(substr(observation_date, 1, 4)))

ppi_data <- ppi_data %>%
  group_by(year) %>%
  summarise(wpu01 = mean(WPU01))

# change base to 2012

ppi_2012 <- ppi_data$wpu01[ppi_data$year == 2012]

ppi_data <- ppi_data %>%
  mutate(ppi_2012 = wpu01 / ppi_2012)

ggplot(data = ppi_data, aes(y = ppi_2012, x = year)) +
  geom_line()

ppi_data <- ppi_data %>%
  select(year, ppi_2012)

write_parquet(ppi_data, path_processed("ppi_2012.parquet"))

## County Boundary ------------------------------------

# cleaned in the original stata file
state_border_pairs <- read_csv(
  file = path_raw("geographic_crosswalks", "state_border_pairs.csv")
)
border_counties_allmatches <- read_csv(
  file = path_raw("geographic_crosswalks", "border_counties_allmatches.csv")
)

full_county_set <- read_parquet(path_int("county_adjacency2010.parquet"))

# state minimum wages --------------------------------------

head(state_min_alt) # want the dummy from here
head(state_minwages)
# deflate by ppi

state_min_alt <- state_min_alt %>%
  mutate(fips = as.numeric(state_fips_code)) %>%
  filter(year == 2024) %>% # these are stable, so ignore them
  select(fips, agriculture_exemption)

state_minwage_ppi <- merge(
  x = state_minwages,
  y = ppi_data,
  by = "year",
  all.x = T,
  all.y = F
)

state_minwage_ppi <- merge(
  x = state_minwage_ppi,
  y = state_min_alt,
  by = "fips",
  all.x = T,
  all.y = F
)

state_minwage_ppi$agriculture_exemption[is.na(
  state_minwage_ppi$agriculture_exemption
)] <- TRUE

# make the prevailing ag min wage #

# fill in state min with federal if missing #

state_minwage_ppi <- state_minwage_ppi %>%
  transform(
    state_min_wage = ifelse(
      !is.na(state_min_wage),
      state_min_wage,
      federal_min_wage
    )
  )

state_minwage_ppi <- state_minwage_ppi %>%
  mutate(
    prevailing_ag_min_wage = ifelse(
      agriculture_exemption == T,
      federal_min_wage,
      pmax(state_min_wage, federal_min_wage, na.rm = TRUE)
    )
  )

state_minwage_ppi <- state_minwage_ppi %>%
  mutate(
    prevailing_min_wage_ppi = prevailing_min_wage / ppi_2012,
    prevailing_ag_min_wage_ppi = prevailing_ag_min_wage / ppi_2012,
    federal_min_wage_ppi = federal_min_wage / ppi_2012,
    state_min_wage_ppi = state_min_wage / ppi_2012
  ) %>%
  dplyr::select(-ppi_2012)

gc()

write_parquet(
  state_minwage_ppi,
  path_processed("state_real_minwages.parquet")
)

