# Generated by code/split_do_r_scripts.py.
# Edit the source Do script or split specification, then regenerate.
# Source: Do/H2A Clean and Load.R lines 200-419
# Source SHA256: 6f06da41f3d01c670a28623219b5ca27b525147e08d8891e4e841ff4d66f4f49

if (!exists("path_processed", mode = "function")) {
  local({
    split_current_file <- function() {
      frames <- sys.frames()
      for (idx in rev(seq_along(frames))) {
        ofile <- frames[[idx]]$ofile
        if (!is.null(ofile)) {
          return(normalizePath(ofile, winslash = "/", mustWork = FALSE))
        }
      }

      file_arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)
      if (length(file_arg) > 0) {
        return(normalizePath(sub("^--file=", "", file_arg[[1]]), winslash = "/", mustWork = FALSE))
      }

      normalizePath(getwd(), winslash = "/", mustWork = FALSE)
    }

    source(file.path(dirname(split_current_file()), "c00_setup.R"))
  })
}

## H2A Data -------------------------------------------
h2a_data <- read_parquet(
  file = path_int("h2a_aggregated.parquet")
)
h2a_predict <- read_parquet(
  file = path_int("h2a_prediction_using_elastic_net_continuous_basis.parquet")
) %>%
  mutate(
    countyfips = split_fips5(county_ansi)
  ) %>%
  select(-county_ansi) %>%
  write_parquet(path_processed("h2a_predict.parquet"))

# census period
h2a_data <- h2a_data %>%
  mutate(
    census_period = ifelse(
      year >= 2008 & year < 2012,
      2012,
      ifelse(
        year >= 2012 & year < 2017,
        2017,
        ifelse(year >= 2017 & year < 2022, 2022, NA)
      )
    )
  )


# fix fips code

h2a_data <- h2a_data %>%
  mutate(
    cnty_fips_string = str_pad(
      as.character(county_fips_code),
      width = 3,
      side = "left",
      pad = "0"
    ),
    st_fips_string = str_pad(
      as.character(state_fips_code),
      width = 2,
      side = "left",
      pad = "0"
    )
  )

h2a_data <- h2a_data %>%
  mutate(countyfips = split_fips5(paste0(st_fips_string, cnty_fips_string)))


# clean by dropping old codes #

h2a_data <- h2a_data %>%
  filter(!is.na(census_period) & !is.na(county_fips_code)) %>%
  select(
    -cnty_fips_string,
    -st_fips_string,
    -state_fips_code,
    -county_fips_code
  )

# collapse by period, county (county and state fips)
h2a_prediction <- h2a_data %>%
  select(countyfips)

h2a_data <- h2a_data %>%
  group_by(census_period, countyfips) %>%
  summarise(
    nbr_workers_requested_all_years = sum(
      nbr_workers_requested_all_years,
      na.rm = T
    ),
    nbr_workers_certified_all_years = sum(
      nbr_workers_certified_all_years,
      na.rm = T
    ),
    man_hours_requested_all_years = sum(
      man_hours_requested_all_years,
      na.rm = T
    ),
    man_hours_certified_all_years = sum(
      man_hours_certified_all_years,
      na.rm = T
    ),
    nbr_applications_all_years = sum(nbr_applications_all_years, na.rm = T),
    nbr_workers_requested_start_year = sum(
      nbr_workers_requested_start_year,
      na.rm = T
    ),
    nbr_workers_certified_start_year = sum(
      nbr_workers_certified_start_year,
      na.rm = T
    ),
    man_hours_requested_start_year = sum(
      man_hours_requested_start_year,
      na.rm = T
    ),
    man_hours_certified_start_year = sum(
      man_hours_certified_start_year,
      na.rm = T
    ),
    nbr_applications_start_year = sum(nbr_applications_start_year, na.rm = T),
    nbr_workers_requested_fiscal_year = sum(
      nbr_workers_requested_fiscal_year,
      na.rm = T
    ),
    nbr_workers_certified_fiscal_year = sum(
      nbr_workers_certified_fiscal_year,
      na.rm = T
    ),
    man_hours_requested_fiscal_year = sum(
      man_hours_requested_fiscal_year,
      na.rm = T
    ),
    man_hours_certified_fiscal_year = sum(
      man_hours_certified_fiscal_year,
      na.rm = T
    ),
    nbr_applications_fiscal_year = sum(nbr_applications_fiscal_year, na.rm = T)
  )


write_parquet(h2a_data, path_processed("h2a_data.parquet"))

# yearly, for TS

h2a_data_ts <- read_parquet(
  path_int("h2a_aggregated.parquet"),
  stringsAsFactors = F
)

h2a_data_ts <- h2a_data_ts %>%
  group_by(year) %>%
  summarise(
    h2a_man_hours_certified = sum(man_hours_certified_start_year, na.rm = T),
    h2a_man_hours_requested = sum(man_hours_requested_start_year, na.rm = T),
    h2a_nbr_workers_certified = sum(
      nbr_workers_certified_start_year,
      na.rm = T
    ),
    h2a_nbr_workers_requested = sum(
      nbr_workers_requested_start_year,
      na.rm = T
    ),
    n_applications = sum(nbr_applications_start_year, na.rm = T)
  )


h2a_data_ts <- h2a_data_ts %>%
  rename(case_year = year)

write_parquet(h2a_data_ts, path_processed("h2a_data_ts.parquet"))

## Cropland Crocs Data Layer (CDL) -------------------------------------------

cdl_codes <- read_csv(
  file = path_raw("croplandcros_cdl", "croplandcros_cdl_crop_category.csv")
)

cdl_data <- read_parquet(path_int("croplandcros_county_crop_acres.parquet"))
head(cdl_data)
# need to put this in a wider format

head(cdl_codes)

cdl_data <- merge(
  x = cdl_data,
  y = cdl_codes,
  by = "crop_name",
  all.x = T,
  all.y = F
)

head(cdl_data)

cdl_data_collapse <- cdl_data %>%
  group_by(crop_type, year, fips) %>%
  summarise(
    acres = sum(acres, na.rm = T),
    crop_count = n()
  )

head(cdl_data_collapse)

cdl_data_collapse <- cdl_data_collapse %>%
  pivot_wider(
    id_cols = c("fips", "year"),
    names_from = "crop_type",
    values_from = c("acres", "crop_count")
  )

head(cdl_data_collapse)

cdl_data_collapse[is.na(cdl_data_collapse)] <- 0 # NAs are zeros

cdl_data_collapse <- cdl_data_collapse %>%
  ungroup() %>%
  mutate(countyfips = split_fips5(fips)) %>%
  dplyr::select(-fips)

write_parquet(cdl_data_collapse, path_processed("cdl_cropshares.parquet"))

## NAWSPAD ---------------------------------------------
# state level data
nawspad_data <- read_parquet(
  path_int("nawspad.parquet"),
  stringsAsFactors = F
)

nawspad_data %>%
  group_by(crop_type) %>%
  tally()

## OEWS ------------------------------------------------
# wages
oews_agg_data <- read_parquet(
  file = path_int("oews_county_aggregated.parquet"),
  stringsAsFactors = F
)

