# Generated by code/split_do_r_scripts.py.
# Edit the source Do script or split specification, then regenerate.
# Source: Do/H2A Clean and Load.R lines 755-955
# Source SHA256: 357bbeaef9d9eb6e731cd6af89253339e71ec57415a2d03f87af45a50652c6fb
rm(list = ls())
if (!exists("path_code", mode = "function")) {
  source(file.path("code", "paths.R"))
}
if (!exists("split_fips5", mode = "function")) {
  source(path_code("c00_setup.R"))
}

## AEWR Region TS --------------------------------------------------------------

dir.create(path_figures("aewr_ts"), recursive = TRUE, showWarnings = FALSE)

aewr_data <- read_parquet(path_processed("aewr_data_full.parquet"))

split_save_aewr_region_ts(aewr_data, "ln_aewr", "Log AEWR (nominal)", "ts_ln_aewr_nominal_")
split_save_aewr_region_ts(aewr_data, "ln_aewr_l1", "Log Change AEWR (nominal)", "ts_ln_aewr_l1_nominal_")
split_save_aewr_region_ts(aewr_data, "aewr_diff", "AEWR (nominal) difference from LOO trend", "ts_aewr_diffloo_nominal_")
split_save_aewr_region_ts(aewr_data, "aewr_ppi_diff", "AEWR (real) difference from LOO trend", "ts_aewr_diffloo_real_")
split_save_aewr_region_ts(aewr_data, "aewr", "AEWR (nominal)", "ts_aewr_nominal_")
split_save_aewr_region_ts(aewr_data, "aewr_ppi", "AEWR (real)", "ts_aewr_real_")
split_save_aewr_region_ts(aewr_data, "ch_aewr", "Change AEWR (nominal)", "ts_change_aewr_nominal_")
split_save_aewr_region_ts(aewr_data, "ch_aewr_ppi", "Change AEWR (real)", "ts_change_aewr_real_")
split_save_aewr_region_ts(aewr_data, "pch_aewr", "Percent Change AEWR (nominal)", "ts_percentchange_aewr_nominal_")
split_save_aewr_region_ts(aewr_data, "pch_aewr_ppi", "Percent Change AEWR (real)", "ts_percentchange_aewr_real_")

combo_plot <- ggplot(
  data = aewr_data,
  aes(
    x = year,
    y = pch_aewr,
    group = as.factor(aewr_region_num),
    color = as.factor(aewr_region_num)
  )
) +
  geom_line() +
  geom_vline(xintercept = 2007)
combo_plot


