# Generated by code/split_do_r_scripts.py.
# Edit the source Do script or split specification, then regenerate.
# Source: Do/H2A Build Dataset.R lines 944-972
# Source SHA256: 29c4c238e6463b7d8b0dead1f2780b2a7f805557370931a54c1dc0067e5774a7
rm(list = ls())
if (!exists("path_code", mode = "function")) {
  source(file.path("code", "paths.R"))
}
if (!exists("split_fips5", mode = "function")) {
  source(path_code("c00_setup.R"))
}

# --- Diagnostic: county_df_analysis_year ---
county_df <- read_parquet(path_processed("county_df_analysis_year.parquet"))
cat("county_df rows:", nrow(county_df), " | cols:", ncol(county_df), "\n")
stopifnot(nrow(county_df) > 10000)
stopifnot(all(
  c(
    "aewr_state_ag_ppi_l1",
    "high_h2a_share_75",
    "high_h2a_share_75_inverse",
    "h2a_cert_share_farm_workers_2011_start_year",
    "county_fe",
    "year_fe",
    "statefips",
    "ln_pop_census",
    "emp_pop_ratio"
  ) %in%
    names(county_df)
))
cat("Diagnostic passed: county_df_analysis_year\n")

## Remove files ## -------------------------------------------------------------

str_detect(ls(), "folder_")

objects <- data.frame(name = ls(), keep = str_detect(ls(), "folder_")) %>%
  filter(keep == F)

rm(list = objects[, 1])
gc()
rm(objects)
