# Generated by code/split_do_r_scripts.py.
# Edit the source Do script or split specification, then regenerate.
# Source: Do/H2A Build Dataset.R lines 1-272
# Source SHA256: f6618f3dc3db60bebde02ba3da2fcee94ecad4f724e9505944b132b623f90ff8
rm(list = ls())
if (!exists("path_code", mode = "function")) {
  source(file.path("code", "paths.R"))
}
if (!exists("split_fips5", mode = "function")) {
  source(path_code("c00_setup.R"))
}

## H2A Build Dataset
## Phil Hoxie
## 1/31/24
ensure_project_dirs()
library(tidyverse)
library(arrow)
library(tidylog, warn.conflicts = FALSE)

## Yearly Full County Dataset ------------------------------------------------

## ------- Full County ----------------------------------------------------------------------
## Yearly Dataset ## -----------------------------------------------------------
## -------- Full County -----------------------------------------------------------

## Load Data -------------------------------------------------------------------

# yearly versions #
aewr_data <- read_parquet(path_int("aewr_data_year.parquet"))
aewr_regions <- read_csv(
  file = path_raw("geographic_crosswalks", "phil", "aewr_regions.csv")
)
bea_caemp25n_data <- read_parquet(path_int("bea_caemp25n_data_year.parquet"))
bea_cainc45_data <- read_parquet(path_int("bea_cainc45_data_year.parquet"))
fips_codes <- read_csv(
  file = path_raw("geographic_crosswalks", "phil", "fips_codes.csv")
)
fips_codes <- fips_codes %>%
  mutate(fips = split_fips2(fips))
h2a_data <- read_parquet(path_int("h2a_data_year.parquet"))
h2a_predict <- read_parquet(path_int("h2a_predict.parquet"))
census_of_agriculture_cropland <- read_parquet(path_int("census_ag_cropland_year.parquet"))

census_pop_ests <- read_parquet(path_int("census_pop_ests_year.parquet"))

census_of_agriculture_cropland_base <- read_parquet(path_int("census_ag_cropland_2007_year.parquet"))

state_min <- read_parquet(path_int("state_real_minwages.parquet"))

cz_wage_quantiles <- read_parquet(path_int(
  "acs_czone_wage_quantiles.parquet"
))

ppi_annual <- read_parquet(path_int("ppi_2012.parquet"))

nass_price_index <- read_parquet(path_int("nass_fisher_price_index.parquet"))

# base for full county dataset

county_df <- read_parquet(path_int("county_df_year.parquet"))

# CZ

cz_file_small <- read_parquet(path_int("cz_file_2010_small.parquet"))

head(county_df)

county_df %>% group_by(year) %>% tally()

# merge in for each side:

# by state and year
head(aewr_data)

# by state
head(aewr_regions)

# merge for only one side

# by
# loop ?

# by county and census_period

head(bea_caemp25n_data)
head(bea_cainc45_data)
head(h2a_data)
head(census_pop_ests)

## a tad of prep ---------------------------------------------------------------

class(county_df$fipscounty)

# make state fips

county_df <- county_df %>%
  mutate(
    fipscounty = split_fips5(fipscounty),
    statefips = split_state_from_countyfips(fipscounty)
  )

hist(as.integer(county_df$statefips)) # it worked!

## both sides merge ----------------------------------------------------------

# fips first

county_df <- merge(
  x = county_df,
  y = fips_codes,
  by.x = "statefips",
  by.y = "fips",
  all.x = T,
  all.y = F
)

county_df <- county_df %>%
  filter(as.integer(statefips) <= 56) # only states

# first side

names(aewr_data)

dim(county_df)

county_df <- merge(
  x = county_df,
  y = aewr_data,
  by = c("year", "state_abbrev"),
  all.x = T,
  all.y = F
)

dim(county_df) # DC missing

head(county_df)
# no need to rename these

names(aewr_regions)
dim(county_df)

county_df <- merge(
  x = county_df,
  y = aewr_regions,
  by = c("state_abbrev"),
  all.x = T,
  all.y = F
)

dim(county_df)

county_df <- county_df %>%
  rename(countyfips = fipscounty)

datasets <- c(
  "bea_caemp25n_data",
  "bea_cainc45_data",
  "h2a_data",
  "census_pop_ests",
  "census_of_agriculture_cropland",
  "nass_price_index"
)

for (i in 1:length(datasets)) {
  print(paste0("Rep ", i))
  temp <- get(datasets[i])
  print(dim(county_df))
  print(dim(temp))
  county_df <- merge(
    x = county_df,
    y = temp,
    by = c("year", "countyfips"),
    all.x = T,
    all.y = F
  )
  rm(temp)
}

county_df <- county_df %>%
  left_join(h2a_predict, by = "countyfips")

dim(county_df)
head(county_df)

# county only #

dim(census_of_agriculture_cropland_base)

county_df <- merge(
  x = county_df,
  y = census_of_agriculture_cropland_base,
  by = "countyfips",
  all.x = T,
  all.y = F
)

county_df %>%
  group_by(year) %>%
  tally()

county_df %>%
  filter(year == 2008 & !is.na(cropland_acr_2007)) %>%
  count()

# add in minimum wages

head(state_min)

state_min <- state_min %>%
  rename(statefips = fips)

# make a few lags

state_min <- state_min %>%
  arrange(statefips, year) %>%
  group_by(statefips) %>%
  mutate(across(names(state_min)[3:11], lag, .names = "{.col}_l1"))

county_df <- merge(
  x = county_df,
  y = state_min,
  by = c("statefips", "year"),
  all.x = T,
  all.y = F
)

# add in wage quantiles
# annual data starts 2005
cz_wage_quantiles <- cz_wage_quantiles %>%
  rename(year = YEAR, cz_1990 = czone) %>%
  mutate(countyfips = split_fips5(county_ansi)) %>%
  filter(year >= 2005) %>%
  select(-county_ansi)

# Deflate wage percentiles to real 2012 terms using PPI WPU01 (rebased 2012=100)
# aewr_ppi is real; wage_p* must also be real before computing bite variables
cz_wage_quantiles <- cz_wage_quantiles %>%
  left_join(ppi_annual, by = "year") %>%
  mutate(across(
    c(wage_p10, wage_p25, wage_p50, wage_p75, wage_p90),
    ~ . / ppi_2012
  )) %>%
  select(-ppi_2012)

# Add lags as in state minimum wages
cz_wage_quantiles <- cz_wage_quantiles %>%
  group_by(countyfips) %>%
  mutate(across(
    names(cz_wage_quantiles)[3:7],
    lag,
    .names = "{.col}_l1",
    order_by = year
  ))

county_df <- merge(
  x = county_df,
  y = cz_wage_quantiles,
  by = c("countyfips", "year"),
  all.x = T,
  all.y = F
)

# deflate fisher price index to real 2012 terms
# ppi_2012 is already present in county_df via bea_cainc45_data_year merge
county_df <- county_df %>%
  mutate(fisher_index_ppi = fisher_index / ppi_2012)

write_parquet(county_df, path_int("county_df_build_merge.parquet"))
cat("county_df_build_merge:", nrow(county_df), "rows,", ncol(county_df), "cols\n")

