# Generated by code/split_do_r_scripts.py.
# Edit the source Do script or split specification, then regenerate.
# Source: Do/H2A Analysis Figs and Tables.R lines 1962-2596
# Source SHA256: be3b3b11f809e62d7b3192f38a4b05aab1a0b0444d8d16ba7c5fa3f56e07e5a9
rm(list = ls())
if (!exists("path_code", mode = "function")) {
  source(file.path("code", "paths.R"))
}
if (!exists("split_fips5", mode = "function")) {
  source(path_code("c00_setup.R"))
}

#### Exhibit 21: Stacked Matched Staggered DiD — Treatment Classification ------

split_load_analysis_inputs(
  include_county_df = TRUE,
  include_samples = TRUE
)

## Step 1: Sample and % change variable ----------------------------------------

EVENT_WINDOW <- 3

stacked_sample <- county_df %>%
  filter(
    any_cropland_2007 == 1,
    county_simple_treatment_groups != "always takers"
  ) %>%
  arrange(countyfips, year) %>%
  mutate(
    aewr_cz_p25_pd1 = (aewr_cz_p25 - aewr_cz_p25_l1) / aewr_cz_p25_l1
    # Inf when aewr_cz_p25_l1 == 0; filtered below
  )

## Step 2: Quartile thresholds from finite observations ------------------------

pd1_clean <- stacked_sample %>%
  filter(!is.na(aewr_cz_p25_pd1), is.finite(aewr_cz_p25_pd1))

q25_cut <- quantile(pd1_clean$aewr_cz_p25_pd1, 0.25)
q75_cut <- quantile(pd1_clean$aewr_cz_p25_pd1, 0.75)
cat("Stacked DiD thresholds (% change in AEWR-CZ p25 bite):\n")
cat("  q25 (large decrease threshold):", round(q25_cut, 4), "\n")
cat("  q75 (large increase threshold):", round(q75_cut, 4), "\n")
cat("  N obs (finite):", nrow(pd1_clean), "of", nrow(stacked_sample), "\n")

## Step 3: Tag large changes by county-year ------------------------------------

events_df <- stacked_sample %>%
  mutate(
    large_increase = !is.na(aewr_cz_p25_pd1) &
      is.finite(aewr_cz_p25_pd1) &
      aewr_cz_p25_pd1 >= q75_cut,
    large_decrease = !is.na(aewr_cz_p25_pd1) &
      is.finite(aewr_cz_p25_pd1) &
      aewr_cz_p25_pd1 <= q25_cut
  )

## Step 4: County-level event classification -----------------------------------

county_events <- events_df %>%
  group_by(countyfips) %>%
  summarise(
    first_increase_year = if (any(large_increase, na.rm = TRUE)) {
      min(year[large_increase], na.rm = TRUE)
    } else {
      NA_integer_
    },
    first_decrease_year = if (any(large_decrease, na.rm = TRUE)) {
      min(year[large_decrease], na.rm = TRUE)
    } else {
      NA_integer_
    },
    .groups = "drop"
  ) %>%
  mutate(
    tied = !is.na(first_increase_year) &
      !is.na(first_decrease_year) &
      first_increase_year == first_decrease_year,
    t_increase = case_when(
      tied ~ 0L,
      !is.na(first_increase_year) & is.na(first_decrease_year) ~ 1L,
      !is.na(first_increase_year) &
        first_increase_year < first_decrease_year ~ 1L,
      TRUE ~ 0L
    ),
    t_decrease = case_when(
      tied ~ 0L,
      !is.na(first_decrease_year) & is.na(first_increase_year) ~ 1L,
      !is.na(first_decrease_year) &
        first_decrease_year < first_increase_year ~ 1L,
      TRUE ~ 0L
    ),
    y_increase = ifelse(t_increase == 1L, first_increase_year, NA_integer_),
    y_decrease = ifelse(t_decrease == 1L, first_decrease_year, NA_integer_),
    never_treated = (t_increase == 0L & t_decrease == 0L & !tied)
  )

valid_event_min <- min(stacked_sample$year, na.rm = TRUE) + EVENT_WINDOW
valid_event_max <- max(stacked_sample$year, na.rm = TRUE) - EVENT_WINDOW

county_events <- county_events %>%
  mutate(
    eligible_increase = t_increase == 1L &
      !is.na(y_increase) &
      y_increase >= valid_event_min &
      y_increase <= valid_event_max,
    eligible_decrease = t_decrease == 1L &
      !is.na(y_decrease) &
      y_decrease >= valid_event_min &
      y_decrease <= valid_event_max
  )

cat("\n=== County event classification ===\n")
cat("Increase counties (t_increase=1):", sum(county_events$t_increase), "\n")
cat("Decrease counties (t_decrease=1):", sum(county_events$t_decrease), "\n")
cat(
  "Eligible increase counties (full event window):",
  sum(county_events$eligible_increase, na.rm = TRUE),
  "\n"
)
cat(
  "Eligible decrease counties (full event window):",
  sum(county_events$eligible_decrease, na.rm = TRUE),
  "\n"
)
cat("Tied (excluded from both):", sum(county_events$tied, na.rm = TRUE), "\n")
cat(
  "Never-treated (controls):",
  sum(county_events$never_treated, na.rm = TRUE),
  "\n"
)
cat("Total counties:", nrow(county_events), "\n")

## Step 5: Subsequent change variables ----------------------------------------

increase_subsequent <- events_df %>%
  inner_join(
    county_events %>%
      filter(t_increase == 1L) %>%
      select(countyfips, y_increase),
    by = "countyfips"
  ) %>%
  filter(year > y_increase) %>%
  group_by(countyfips) %>%
  summarise(
    subsequent_n_increases = sum(large_increase, na.rm = TRUE),
    y_next_increase = if (any(large_increase, na.rm = TRUE)) {
      min(year[large_increase], na.rm = TRUE)
    } else {
      NA_integer_
    },
    n_decreases_post_increase = sum(large_decrease, na.rm = TRUE),
    y_first_decrease_post_increase = if (any(large_decrease, na.rm = TRUE)) {
      min(year[large_decrease], na.rm = TRUE)
    } else {
      NA_integer_
    },
    .groups = "drop"
  )

decrease_subsequent <- events_df %>%
  inner_join(
    county_events %>%
      filter(t_decrease == 1L) %>%
      select(countyfips, y_decrease),
    by = "countyfips"
  ) %>%
  filter(year > y_decrease) %>%
  group_by(countyfips) %>%
  summarise(
    subsequent_n_decreases = sum(large_decrease, na.rm = TRUE),
    y_next_decrease = if (any(large_decrease, na.rm = TRUE)) {
      min(year[large_decrease], na.rm = TRUE)
    } else {
      NA_integer_
    },
    n_increases_post_decrease = sum(large_increase, na.rm = TRUE),
    y_first_increase_post_decrease = if (any(large_increase, na.rm = TRUE)) {
      min(year[large_increase], na.rm = TRUE)
    } else {
      NA_integer_
    },
    .groups = "drop"
  )

county_events <- county_events %>%
  left_join(increase_subsequent, by = "countyfips") %>%
  left_join(decrease_subsequent, by = "countyfips")

cat("\n=== Subsequent changes (increase counties) ===\n")
print(table(
  county_events$subsequent_n_increases[county_events$t_increase == 1L],
  useNA = "ifany"
))
cat("\n=== Subsequent changes (decrease counties) ===\n")
print(table(
  county_events$subsequent_n_decreases[county_events$t_decrease == 1L],
  useNA = "ifany"
))

#### Exhibit 21b: Treatment status by year figure ------------------------------
# Motivates the "not-yet-treated" control group strategy.
# Blue = not-yet-treated counties in the same design (proposed control pool).

status_data <- stacked_sample %>%
  select(countyfips, year) %>%
  inner_join(
    county_events %>%
      select(
        countyfips,
        t_increase,
        t_decrease,
        tied,
        never_treated,
        first_increase_year,
        first_decrease_year
      ),
    by = "countyfips"
  ) %>%
  mutate(
    status_increase = case_when(
      t_increase == 1L & year >= first_increase_year ~ "Already treated",
      t_increase == 1L & year < first_increase_year ~ "Not yet treated",
      t_decrease == 1L ~ "First change is decrease",
      never_treated ~ "Never treated",
      TRUE ~ "Other (tied)"
    ),
    status_decrease = case_when(
      t_decrease == 1L & year >= first_decrease_year ~ "Already treated",
      t_decrease == 1L & year < first_decrease_year ~ "Not yet treated",
      t_increase == 1L ~ "First change is increase",
      never_treated ~ "Never treated",
      TRUE ~ "Other (tied)"
    )
  )

share_increase <- status_data %>%
  group_by(year, status = status_increase) %>%
  summarise(n = n_distinct(countyfips), .groups = "drop") %>%
  group_by(year) %>%
  mutate(share = n / sum(n), design = "Large increase design") %>%
  ungroup()

share_decrease <- status_data %>%
  group_by(year, status = status_decrease) %>%
  summarise(n = n_distinct(countyfips), .groups = "drop") %>%
  group_by(year) %>%
  mutate(share = n / sum(n), design = "Large decrease design") %>%
  ungroup()

status_combined <- bind_rows(share_increase, share_decrease) %>%
  mutate(
    status = factor(
      status,
      levels = c(
        "Already treated",
        "Not yet treated",
        "First change is decrease",
        "First change is increase",
        "Never treated",
        "Other (tied)"
      )
    )
  )

# Print not-yet-treated pool size at key years
cat("\n=== Not-yet-treated pool size (increase design) ===\n")
pool_inc <- share_increase %>%
  filter(status == "Not yet treated") %>%
  select(year, n) %>%
  arrange(year)
print(pool_inc)

cat("\n=== Not-yet-treated pool size (decrease design) ===\n")
pool_dec <- share_decrease %>%
  filter(status == "Not yet treated") %>%
  select(year, n) %>%
  arrange(year)
print(pool_dec)

fig_treatment_status <- ggplot(
  status_combined,
  aes(x = year, y = share, fill = status)
) +
  geom_col(position = "stack", width = 0.85) +
  scale_fill_manual(
    values = c(
      "Already treated" = "#d62728",
      "Not yet treated" = "#1f77b4",
      "First change is decrease" = "#ff7f0e",
      "First change is increase" = "#2ca02c",
      "Never treated" = "#7f7f7f",
      "Other (tied)" = "#bcbd22"
    ),
    drop = FALSE
  ) +
  scale_x_continuous(breaks = seq(2008, 2022, 2)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  facet_wrap(~design, ncol = 1) +
  labs(
    title = "Treatment Group Status by Year",
    x = "Year",
    y = "Share of counties",
    fill = NULL
  ) +
  theme_minimal(base_size = 11) +
  theme(legend.position = "bottom", legend.text = element_text(size = 9))

ggsave(
  filename = path_figures("fig_stacked_dd_treatment_status_by_year.png"),
  plot = fig_treatment_status,
  width = 9,
  height = 7,
  dpi = 300
)
cat("\nSaved: fig_stacked_dd_treatment_status_by_year.png\n")

#### Exhibit 22: Correlation Matrix → Excel ------------------------------------

corr_vars <- c(
  "aewr_cz_p25_l1",
  "h2a_cert_share_farm_workers_2011_start_year",
  "nbr_workers_certified_start_year_l1",
  "ln_pop_census",
  "emp_pop_ratio",
  "share_farm_crop_cashandinc",
  "share_farm_animal_cashandinc",
  "share_farm_laborexp_prodexp",
  "emp_farm",
  "fisher_index_ppi"
)

corr_data <- samp_base %>%
  filter(year <= 2011) %>%
  select(all_of(corr_vars)) %>%
  mutate(across(everything(), ~ as.numeric(scale(.)))) %>%
  filter(if_all(everything(), ~ !is.na(.) & is.finite(.)))

corr_matrix <- cor(corr_data)

write_xlsx(
  as.data.frame(round(corr_matrix, 3)) %>%
    tibble::rownames_to_column("variable"),
  path = path_tables("corr_matrix_matching_controls.xlsx")
)

cat("\n=== Correlation matrix (z-scored, pre-2012 obs) ===\n")
print(round(corr_matrix, 2))

#### Exhibit 23: Propensity Score Matching -------------------------------------
# Review corr_matrix_matching_controls.xlsx before running.
# Edit PSM_VARS to swap covariates in/out. Avoid pairs with |r| > 0.7.
# All variables are z-scored before matching (MatchIt does NOT do this itself).

PSM_VARS <- c(
  "aewr_cz_p25_l1",
  "h2a_cert_share_farm_workers_2011_start_year",
  "ln_pop_census",
  "emp_pop_ratio",
  "share_farm_crop_cashandinc",
  "share_farm_laborexp_prodexp"
)

psm_base_cs <- samp_base %>%
  filter(year == 2011) %>%
  distinct(countyfips, .keep_all = TRUE) %>%
  select(countyfips, all_of(PSM_VARS)) %>%
  inner_join(
    county_events %>%
      select(
        countyfips,
        t_increase,
        t_decrease,
        eligible_increase,
        eligible_decrease,
        never_treated,
        tied
      ),
    by = "countyfips"
  ) %>%
  filter(!tied) %>%
  mutate(across(all_of(PSM_VARS), ~ as.numeric(scale(.))))

run_psm <- function(psm_df, treatment_col, label) {
  treated_n <- sum(psm_df[[treatment_col]] == 1L, na.rm = TRUE)
  control_n <- sum(psm_df[[treatment_col]] == 0L, na.rm = TRUE)

  cat("\n=== PSM Balance:", label, "group ===\n")

  if (treated_n == 0L || control_n == 0L) {
    cat(
      "Skipped: need both treated and controls after the event-window filter; ",
      "treated = ",
      treated_n,
      ", controls = ",
      control_n,
      "\n",
      sep = ""
    )
    return(list(model = NULL, matched = NULL))
  }

  model <- matchit(
    reformulate(PSM_VARS, response = treatment_col),
    data = psm_df,
    method = "nearest",
    ratio = 1,
    distance = "logit"
  )

  print(summary(model, standardize = TRUE))

  list(model = model, matched = match.data(model))
}

# --- Increase group vs never-treated ---
psm_df_increase <- psm_base_cs %>%
  filter(eligible_increase | never_treated) %>%
  filter(if_all(all_of(PSM_VARS), ~ !is.na(.) & is.finite(.)))

psm_increase <- run_psm(psm_df_increase, "t_increase", "Increase")
m_increase <- psm_increase$model
matched_increase <- psm_increase$matched

# --- Decrease group vs never-treated ---
psm_df_decrease <- psm_base_cs %>%
  filter(eligible_decrease | never_treated) %>%
  filter(if_all(all_of(PSM_VARS), ~ !is.na(.) & is.finite(.)))

psm_decrease <- run_psm(psm_df_decrease, "t_decrease", "Decrease")
m_decrease <- psm_decrease$model
matched_decrease <- psm_decrease$matched

#### Exhibits 24-27: Stacked DiD Event Studies ---------------------------------
# Specification: i(rel_year, treated, ref = -1) | unit_cohort_id + year^cohort_id
# unit_cohort_id = countyfips × cohort, so control counties that appear in
# multiple cohort stacks get separate unit FEs per cohort (clean stacking).
# Cluster: cz_aewr_region_fe (same as main DD).

empty_stacked_df <- function(full_panel) {
  full_panel[0, , drop = FALSE] %>%
    mutate(
      treated = integer(),
      cohort_id = integer(),
      rel_year = integer(),
      unit_cohort_id = character()
    )
}

make_stacked_df <- function(
  matched_data,
  treatment_col,
  event_year_df,
  full_panel,
  window = EVENT_WINDOW
) {
  if (is.null(matched_data) || nrow(matched_data) == 0L) {
    return(empty_stacked_df(full_panel))
  }

  treated_fips <- matched_data$countyfips[matched_data[[treatment_col]] == 1L]
  control_fips <- unique(matched_data$countyfips[
    matched_data[[treatment_col]] == 0L
  ])

  treated_events <- event_year_df %>%
    filter(countyfips %in% treated_fips)

  year_range <- range(full_panel$year)

  valid_cohorts <- treated_events %>%
    filter(
      !is.na(event_year),
      event_year - window >= year_range[1],
      event_year + window <= year_range[2]
    )

  if (nrow(valid_cohorts) == 0L) {
    return(empty_stacked_df(full_panel))
  }

  stack_list <- lapply(unique(valid_cohorts$event_year), function(ey) {
    cohort_fips <- valid_cohorts$countyfips[valid_cohorts$event_year == ey]

    treat_rows <- full_panel %>%
      filter(
        countyfips %in% cohort_fips,
        year >= ey - window,
        year <= ey + window
      ) %>%
      mutate(treated = 1L, cohort_id = ey, rel_year = year - ey)

    ctrl_rows <- full_panel %>%
      filter(
        countyfips %in% control_fips,
        year >= ey - window,
        year <= ey + window
      ) %>%
      mutate(treated = 0L, cohort_id = ey, rel_year = year - ey)

    bind_rows(treat_rows, ctrl_rows)
  })

  bind_rows(stack_list) %>%
    mutate(unit_cohort_id = paste0(countyfips, "_", cohort_id))
}

stacked_increase <- make_stacked_df(
  matched_data = matched_increase,
  treatment_col = "t_increase",
  event_year_df = county_events %>%
    filter(t_increase == 1L) %>%
    select(countyfips, event_year = y_increase),
  full_panel = stacked_sample
)

stacked_decrease <- make_stacked_df(
  matched_data = matched_decrease,
  treatment_col = "t_decrease",
  event_year_df = county_events %>%
    filter(t_decrease == 1L) %>%
    select(countyfips, event_year = y_decrease),
  full_panel = stacked_sample
)

cat("\n=== Stacked dataset sizes ===\n")
cat("Increase stacked rows:", nrow(stacked_increase), "\n")
cat("Decrease stacked rows:", nrow(stacked_decrease), "\n")

fit_stacked_es <- function(stacked_data, outcome, label) {
  if (nrow(stacked_data) == 0L) {
    cat("Skipping", label, "- no valid stacked cohorts.\n")
    return(NULL)
  }

  feols(
    as.formula(paste0(
      outcome,
      " ~ i(rel_year, treated, ref = -1) | unit_cohort_id + year^cohort_id"
    )),
    data = stacked_data,
    vcov = ~cz_aewr_region_fe
  )
}

es_stacked_h2a_increase <- fit_stacked_es(
  stacked_increase,
  "h2a_cert_share_farm_workers_2011_start_year",
  "H-2A increase event study"
)
es_stacked_h2a_decrease <- fit_stacked_es(
  stacked_decrease,
  "h2a_cert_share_farm_workers_2011_start_year",
  "H-2A decrease event study"
)
es_stacked_price_increase <- fit_stacked_es(
  stacked_increase,
  "fisher_index_ppi",
  "price increase event study"
)
es_stacked_price_decrease <- fit_stacked_es(
  stacked_decrease,
  "fisher_index_ppi",
  "price decrease event study"
)

# Coefficient plots
make_stacked_coefplot <- function(model, title = "") {
  if (is.null(model)) {
    return(NULL)
  }

  cn <- names(coef(model))
  keep <- grep(":treated$", cn, value = TRUE)
  ct <- model$coeftable[keep, , drop = FALSE]

  rel_years_fit <- as.integer(
    sub("^rel_year::([^:]+):treated$", "\\1", rownames(ct))
  )
  all_rel <- sort(unique(c(-1L, rel_years_fit)))

  coeff_df <- data.frame(rel_year = all_rel) %>%
    mutate(
      beta = ifelse(
        rel_year == -1L,
        0,
        ct[match(paste0("rel_year::", rel_year, ":treated"), rownames(ct)), 1]
      ),
      se = ifelse(
        rel_year == -1L,
        0,
        ct[match(paste0("rel_year::", rel_year, ":treated"), rownames(ct)), 2]
      )
    ) %>%
    mutate(upper_ci = beta + 1.96 * se, lower_ci = beta - 1.96 * se)

  ggplot(coeff_df, aes(x = rel_year)) +
    geom_hline(yintercept = 0, color = "grey40") +
    geom_vline(xintercept = -0.5, linetype = "dashed", color = "grey40") +
    geom_ribbon(
      aes(ymin = lower_ci, ymax = upper_ci),
      alpha = 0.2,
      fill = "steelblue"
    ) +
    geom_line(aes(y = beta), color = "steelblue", lwd = 1.2) +
    geom_point(aes(y = beta), color = "steelblue", size = 2) +
    labs(
      x = "Years Relative to Event",
      y = "Coef. (treated × rel_year)",
      title = title
    ) +
    theme_clean() +
    scale_x_continuous(breaks = all_rel)
}

p24 <- make_stacked_coefplot(
  es_stacked_h2a_increase,
  "H-2A Utilization — Large AEWR Bite Increase"
)
p25 <- make_stacked_coefplot(
  es_stacked_h2a_decrease,
  "H-2A Utilization — Large AEWR Bite Decrease"
)
p26 <- make_stacked_coefplot(
  es_stacked_price_increase,
  "Fisher Price Index — Large AEWR Bite Increase"
)
p27 <- make_stacked_coefplot(
  es_stacked_price_decrease,
  "Fisher Price Index — Large AEWR Bite Decrease"
)

save_stacked_plot <- function(plot, filename) {
  if (is.null(plot)) {
    cat("Skipping", filename, "- no valid model.\n")
    return(invisible(NULL))
  }

  ggsave(
    path_figures(filename),
    plot,
    width = 8,
    height = 5,
    device = "png"
  )
}

save_stacked_plot(p24, "coefplot_stacked_dd_h2a_increase.png")
save_stacked_plot(p25, "coefplot_stacked_dd_h2a_decrease.png")
save_stacked_plot(p26, "coefplot_stacked_dd_price_increase.png")
save_stacked_plot(p27, "coefplot_stacked_dd_price_decrease.png")
