# Generated by code/split_do_r_scripts.py.
# Edit the source Do script or split specification, then regenerate.
# Source: Do/H2A Analysis Figs and Tables.R lines 1-48
# Source SHA256: f039e9b3eb25a0ed3f983e7704aa0473d863be9486c970bf8b0067a9e44222ce

if (!exists("path_processed", mode = "function")) {
  local({
    split_current_file <- function() {
      frames <- sys.frames()
      for (idx in rev(seq_along(frames))) {
        ofile <- frames[[idx]]$ofile
        if (!is.null(ofile)) {
          return(normalizePath(ofile, winslash = "/", mustWork = FALSE))
        }
      }

      file_arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)
      if (length(file_arg) > 0) {
        return(normalizePath(sub("^--file=", "", file_arg[[1]]), winslash = "/", mustWork = FALSE))
      }

      normalizePath(getwd(), winslash = "/", mustWork = FALSE)
    }

    source(file.path(dirname(split_current_file()), "c00_setup.R"))
  })
}

## H2A: Analysis Figures and Tables
## Phil Hoxie
## 1/31/24
ensure_project_dirs()

library(arrow)
library(sf)
library(tidyverse)
library(ggspatial)
library(scales)
library(cowplot)
library(ggthemes)
library(fixest)
library(ggfixest)
library(MatchIt)
library(writexl)

set.seed(12345)

split_load_analysis_inputs(
  include_date = TRUE,
  include_shape = TRUE,
  include_h2a_data_ts = TRUE,
  include_h2a_data = TRUE,
  include_aewr_data_full = TRUE,
  include_county_df = TRUE
)

names(county_df)

