# Generated by code/split_do_r_scripts.py.
# Runs the split R pipeline in the same order as the legacy Do master.

split_current_file <- function() {
  frames <- sys.frames()
  for (idx in rev(seq_along(frames))) {
    ofile <- frames[[idx]]$ofile
    if (!is.null(ofile)) {
      return(normalizePath(ofile, winslash = "/", mustWork = FALSE))
    }
  }

  file_arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(file_arg) > 0) {
    return(normalizePath(sub("^--file=", "", file_arg[[1]]), winslash = "/", mustWork = FALSE))
  }

  normalizePath(getwd(), winslash = "/", mustWork = FALSE)
}

split_dir <- dirname(split_current_file())
source(file.path(split_dir, "c00_setup.R"))

source_in_group <- function(files, group_name) {
  message("Running split group: ", group_name)
  group_env <- new.env(parent = globalenv())
  for (file in files) {
    path <- file.path(split_dir, file)
    message("  source ", basename(path))
    sys.source(path, envir = group_env, keep.source = TRUE)
  }
  invisible(group_env)
}

pipeline_groups <- list(
  "pull_min_wages" = c("c01_pull_min_wages.R"),
  "clean_load" = c("c02_clean_01_price_cz_ppi_minwage.R", "c02_clean_02_h2a_cdl_aux.R", "c02_clean_03_yearly_census_h2a_aewr.R", "c02_clean_04_aewr_region_ts_diagnostics.R", "c02_clean_05_bea_population_county_panel.R"),
  "build_dataset" = c("c03_build_01_load_merge.R", "c03_build_02_variable_cleaning.R", "c03_build_03_lags_classification_write.R", "c03_build_04_diagnostics_cleanup.R", "c03_build_05_cz_dissimilar.R"),
  "analysis" = c("c04_analysis_00_setup_data.R", "c04_analysis_01_descriptive_figures.R", "c04_analysis_02_main_dd_event_study.R", "c04_analysis_03_summary_price_labor.R", "c04_analysis_04_stacked_did_matching.R", "c04_analysis_06_cz_dissimilar_iv_diagnostics.R")
)

for (group_name in names(pipeline_groups)) {
  source_in_group(pipeline_groups[[group_name]], group_name)
}
