# Generated by code/split_do_r_scripts.py.
# Shared setup for generated split R modules.

split_current_file <- function() {
  frames <- sys.frames()
  for (idx in rev(seq_along(frames))) {
    ofile <- frames[[idx]]$ofile
    if (!is.null(ofile)) {
      return(normalizePath(ofile, winslash = "/", mustWork = FALSE))
    }
  }

  file_arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(file_arg) > 0) {
    return(normalizePath(sub("^--file=", "", file_arg[[1]]), winslash = "/", mustWork = FALSE))
  }

  normalizePath(getwd(), winslash = "/", mustWork = FALSE)
}

split_dir <- dirname(split_current_file())
code_dir <- normalizePath(file.path(split_dir, ".."), winslash = "/", mustWork = FALSE)
source(file.path(code_dir, "paths.R"))
ensure_project_dirs()
options(stringsAsFactors = FALSE)

suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(fredr))
suppressPackageStartupMessages(library(arrow))
suppressPackageStartupMessages(library(tidylog))
suppressPackageStartupMessages(library(sf))
suppressPackageStartupMessages(library(ggspatial))
suppressPackageStartupMessages(library(scales))
suppressPackageStartupMessages(library(cowplot))
suppressPackageStartupMessages(library(ggthemes))
suppressPackageStartupMessages(library(fixest))
suppressPackageStartupMessages(library(ggfixest))
suppressPackageStartupMessages(library(MatchIt))
suppressPackageStartupMessages(library(writexl))
