# Generated by code/split_do_r_scripts.py.
# Edit the source Do script or split specification, then regenerate.
# Source: Do/H2A Clean and Load.R lines 755-955
# Source SHA256: 357bbeaef9d9eb6e731cd6af89253339e71ec57415a2d03f87af45a50652c6fb

## AEWR Region TS --------------------------------------------------------------

dir.create(path_figures("aewr_ts"), recursive = TRUE, showWarnings = FALSE)

for (i in 1:17) {
  plot <- ggplot(
    data = subset(aewr_data, aewr_region_num == i),
    aes(x = year, y = ln_aewr)
  ) +
    geom_line() +
    labs(title = paste0("AEWR Region Number: ", i)) +
    xlab("Log AEWR (nominal)")
  plot
  ggsave(
    filename = path_figures(
      "aewr_ts",
      paste0("ts_ln_aewr_nominal_", i, ".png")
    ),
    plot,
    device = "png"
  )
  rm(plot)

  plot <- ggplot(
    data = subset(aewr_data, aewr_region_num == i),
    aes(x = year, y = ln_aewr_l1)
  ) +
    geom_line() +
    labs(title = paste0("AEWR Region Number: ", i)) +
    xlab("Log Change AEWR (nominal)")
  plot
  ggsave(
    filename = path_figures(
      "aewr_ts",
      paste0("ts_ln_aewr_l1_nominal_", i, ".png")
    ),
    plot,
    device = "png"
  )
  rm(plot)
}

for (i in 1:17) {
  plot <- ggplot(
    data = subset(aewr_data, aewr_region_num == i),
    aes(x = year, y = aewr_diff)
  ) +
    geom_line() +
    labs(title = paste0("AEWR Region Number: ", i)) +
    xlab("AEWR (nominal) difference from LOO trend")
  plot
  ggsave(
    filename = path_figures(
      "aewr_ts",
      paste0("ts_aewr_diffloo_nominal_", i, ".png")
    ),
    plot,
    device = "png"
  )
  rm(plot)

  plot <- ggplot(
    data = subset(aewr_data, aewr_region_num == i),
    aes(x = year, y = aewr_ppi_diff)
  ) +
    geom_line() +
    labs(title = paste0("AEWR Region Number: ", i)) +
    xlab("AEWR (real) difference from LOO trend")
  plot
  ggsave(
    filename = path_figures(
      "aewr_ts",
      paste0("ts_aewr_diffloo_real_", i, ".png")
    ),
    plot,
    device = "png"
  )
  rm(plot)
}


for (i in 1:17) {
  plot <- ggplot(
    data = subset(aewr_data, aewr_region_num == i),
    aes(x = year, y = aewr)
  ) +
    geom_line() +
    labs(title = paste0("AEWR Region Number: ", i)) +
    xlab("AEWR (nominal)")
  plot
  ggsave(
    filename = path_figures("aewr_ts", paste0("ts_aewr_nominal_", i, ".png")),
    plot,
    device = "png"
  )
  rm(plot)

  plot <- ggplot(
    data = subset(aewr_data, aewr_region_num == i),
    aes(x = year, y = aewr_ppi)
  ) +
    geom_line() +
    labs(title = paste0("AEWR Region Number: ", i)) +
    xlab("AEWR (real)")
  plot
  ggsave(
    filename = path_figures("aewr_ts", paste0("ts_aewr_real_", i, ".png")),
    plot,
    device = "png"
  )
  rm(plot)

  plot <- ggplot(
    data = subset(aewr_data, aewr_region_num == i),
    aes(x = year, y = ch_aewr)
  ) +
    geom_line() +
    labs(title = paste0("AEWR Region Number: ", i)) +
    xlab("Change AEWR (nominal)")
  plot
  ggsave(
    filename = path_figures(
      "aewr_ts",
      paste0("ts_change_aewr_nominal_", i, ".png")
    ),
    plot,
    device = "png"
  )
  rm(plot)

  plot <- ggplot(
    data = subset(aewr_data, aewr_region_num == i),
    aes(x = year, y = ch_aewr_ppi)
  ) +
    geom_line() +
    labs(title = paste0("AEWR Region Number: ", i)) +
    xlab("Change AEWR (real)")
  plot

  ggsave(
    filename = path_figures(
      "aewr_ts",
      paste0("ts_change_aewr_real_", i, ".png")
    ),
    plot,
    device = "png"
  )
  rm(plot)

  plot <- ggplot(
    data = subset(aewr_data, aewr_region_num == i),
    aes(x = year, y = pch_aewr)
  ) +
    geom_line() +
    labs(title = paste0("AEWR Region Number: ", i)) +
    xlab("Percent Change AEWR (nominal)")
  plot
  ggsave(
    filename = path_figures(
      "aewr_ts",
      paste0("ts_percentchange_aewr_nominal_", i, ".png")
    ),
    plot,
    device = "png"
  )
  rm(plot)

  plot <- ggplot(
    data = subset(aewr_data, aewr_region_num == i),
    aes(x = year, y = pch_aewr_ppi)
  ) +
    geom_line() +
    labs(title = paste0("AEWR Region Number: ", i)) +
    xlab("Percent Change AEWR (real)")
  plot

  ggsave(
    filename = path_figures(
      "aewr_ts",
      paste0("ts_percentchange_aewr_real_", i, ".png")
    ),
    plot,
    device = "png"
  )
  rm(plot)
}

combo_plot <- ggplot(
  data = aewr_data,
  aes(
    x = year,
    y = pch_aewr,
    group = as.factor(aewr_region_num),
    color = as.factor(aewr_region_num)
  )
) +
  geom_line() +
  geom_vline(xintercept = 2007)
combo_plot

