# Generated by code/split_do_r_scripts.py.
# Edit the source Do script or split specification, then regenerate.
# Source: Do/H2A Analysis Figs and Tables.R lines 1301-1667
# Source SHA256: e5c7c7d0f8bcd1a11bd8a9d0d23e4c9808ed8b2e17a030a342160d74a4779471

## Exhibit 13: DD Main Results -------------------------------------------------

samp_base <- county_df %>%
  filter(
    any_cropland_2007 == 1,
    county_simple_treatment_groups != "always takers"
  )

cat("samp_base rows:", nrow(samp_base), "\n")
stopifnot(nrow(samp_base) > 1000)

samp_no_border <- samp_base %>% filter(border_cz == 0)

# DD model 1: no controls, all CZs
dd_1 <- feols(
  h2a_cert_share_farm_workers_2011_start_year ~
    aewr_cz_p25_l1 * postdummy | county_fe + year_fe,
  data = samp_base,
  vcov = ~cz_aewr_region_fe,
  demeaned = TRUE
)

dd_1$X_demeaned
xbar = dd_1$X_demeaned
ybar = dd_1$y_demeaned
ybar

samp_base_dd1 <- samp_base %>%
  filter(
    !is.na(h2a_cert_share_farm_workers_2011_start_year),
    !is.na(aewr_cz_p25_l1),
    !is.na(postdummy)
  )

new_table <- bind_cols(samp_base_dd1, xbar) %>%
  mutate(ybar = ybar) %>%
  group_by(year) %>%
  mutate(
    treatment_decile = cut_number(
      aewr_cz_p25_l1...205,
      4,
      labels = c("1", "2", "3", "4")
    )
  ) %>%
  ungroup()

ggplot(new_table, aes(y = ybar, color = treatment_decile)) +
  stat_ecdf(geom = "step", linewidth = 1) +
  coord_cartesian(xlim = c(0.10, 0.90), ylim = c(-0.1, 0.1)) +
  facet_wrap(~year) +
  labs(
    title = "Inverse ECDF / Quantile Plot",
    x = "Quantile (Cumulative Probability)",
    y = "ybar"
  ) +
  theme_minimal()


# DD model 2: with controls, all CZs
dd_2 <- feols(
  h2a_cert_share_farm_workers_2011_start_year ~
    aewr_cz_p25_l1 *
    postdummy +
    ln_pop_census +
    emp_pop_ratio |
    county_fe + year_fe,
  data = samp_base,
  vcov = ~cz_aewr_region_fe
)

# DD model 3: no controls, no border CZs
dd_3 <- feols(
  h2a_cert_share_farm_workers_2011_start_year ~
    aewr_cz_p25_l1 * postdummy | county_fe + year_fe,
  data = samp_no_border,
  vcov = ~cz_aewr_region_fe
)

# DD model 4: with controls, no border CZs
dd_4 <- feols(
  h2a_cert_share_farm_workers_2011_start_year ~
    aewr_cz_p25_l1 *
    postdummy +
    ln_pop_census +
    emp_pop_ratio |
    county_fe + year_fe,
  data = samp_no_border,
  vcov = ~cz_aewr_region_fe
)

# DD model 5: robustness check by excluding potentially influential CZs within each AEWR region
# How many total ag workers are there within each AEWR region?
samp_no_large_cz <- samp_base %>%
  group_by(aewr_region_num, year) %>%
  mutate(aewr_region_year_total_emp_farm = sum(emp_farm, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(cz_fe, year) %>%
  mutate(cz_year_total_emp_farm = sum(emp_farm, na.rm = TRUE)) %>%
  ungroup()

cz_share_of_aewr_region_farm_emp <- samp_no_large_cz %>%
  distinct(aewr_region_num, cz_fe, year, .keep_all = TRUE) %>%
  select(
    aewr_region_num,
    cz_fe,
    year,
    aewr_region_year_total_emp_farm,
    cz_year_total_emp_farm
  ) %>%
  mutate(
    cz_share_farm_emp = cz_year_total_emp_farm / aewr_region_year_total_emp_farm
  )

plot_cz_share_of_aewr_region_farm_emp <- cz_share_of_aewr_region_farm_emp %>%
  ggplot(aes(x = cz_share_farm_emp)) +
  geom_density(fill = "#69b3a2", color = "#e9ecef", alpha = 0.8) +
  xlab("CZ share of total farm employment within AEWR region")

plot_cz_share_of_aewr_region_farm_emp %>%
  ggsave(
    filename = path_figures("cz_share_of_farm_emp_in_aewr_region.png"),
    width = 8,
    height = 5,
    device = "png"
  )

# Pick arbitrary cutoff of 0.1
cz_to_keep_share_below_10 <- cz_share_of_aewr_region_farm_emp %>%
  filter(cz_share_farm_emp < 0.1) %>%
  select(aewr_region_num, cz_fe, year)

samp_cz_share_below_10 <- samp_no_large_cz %>%
  inner_join(cz_to_keep_share_below_10)

dd_5 <- feols(
  h2a_cert_share_farm_workers_2011_start_year ~
    aewr_cz_p25_l1 * postdummy | county_fe + year_fe,
  data = samp_cz_share_below_10,
  vcov = ~cz_aewr_region_fe,
  demeaned = TRUE
)

# What if we just dropped the largest CZ within each AEWR region?
cz_to_keep_not_largest <- cz_share_of_aewr_region_farm_emp %>%
  group_by(aewr_region_num, year) %>%
  filter(cz_share_farm_emp != max(cz_share_farm_emp, na.rm = TRUE))

samp_cz_no_largest <- samp_no_large_cz %>%
  inner_join(cz_to_keep_not_largest)

dd_6 <- feols(
  h2a_cert_share_farm_workers_2011_start_year ~
    aewr_cz_p25_l1 * postdummy | county_fe + year_fe,
  data = samp_cz_no_largest,
  vcov = ~cz_aewr_region_fe,
  demeaned = TRUE
)

# Tables
table_1 <- etable(
  dd_1,
  dd_2,
  dd_3,
  dd_4,
  tex = TRUE,
  title = "The Effect of the AEWR Wage Premium on H-2A Utilization",
  headers = c(
    "No Controls",
    "Controls",
    "No Border, No Controls",
    "No Border, Controls"
  ),
  dict = c(
    "h2a_cert_share_farm_workers_2011_start_year" = "Normalized H-2A program usage",
    "aewr_cz_p25_l1" = "Lagged AEWR vs 25th pct wage gap",
    "postdummy" = "Post",
    "ln_pop_census" = "Log population",
    "emp_pop_ratio" = "Employment-to-pop ratio"
  ),
  signif.code = c("***" = 0.01, "**" = 0.05, "*" = 0.10),
  file = path_tables("table_1_main_results.tex"),
  replace = TRUE
)

summary(dd_1)
summary(dd_2)
summary(dd_3)
summary(dd_4)
summary(dd_5)
summary(dd_6)

## Exhibit 14: Event Study (Flexible DD, Base Year = 2011) --------------------

es_rhs <- paste(
  "aewr_cz_p25_l1 * yeardummy_2008",
  "aewr_cz_p25_l1 * yeardummy_2009",
  "aewr_cz_p25_l1 * yeardummy_2010",
  "aewr_cz_p25_l1 * yeardummy_2012",
  "aewr_cz_p25_l1 * yeardummy_2013",
  "aewr_cz_p25_l1 * yeardummy_2014",
  "aewr_cz_p25_l1 * yeardummy_2015",
  "aewr_cz_p25_l1 * yeardummy_2016",
  "aewr_cz_p25_l1 * yeardummy_2017",
  "aewr_cz_p25_l1 * yeardummy_2018",
  "aewr_cz_p25_l1 * yeardummy_2019",
  "aewr_cz_p25_l1 * yeardummy_2020",
  "aewr_cz_p25_l1 * yeardummy_2021",
  "aewr_cz_p25_l1 * yeardummy_2022",
  sep = " + "
)

es_fml <- as.formula(paste(
  "h2a_cert_share_farm_workers_2011_start_year ~",
  es_rhs,
  "| county_fe + year_fe"
))

es_fml_ctrl <- as.formula(paste(
  "h2a_cert_share_farm_workers_2011_start_year ~",
  es_rhs,
  "+ ln_pop_census + emp_pop_ratio | county_fe + year_fe"
))

# Event study model 1: no controls, all CZs
es_1 <- feols(es_fml, data = samp_base, vcov = ~cz_aewr_region_fe)

# Event study model 2: with controls, all CZs
es_2 <- feols(es_fml_ctrl, data = samp_base, vcov = ~cz_aewr_region_fe)

# Event study model 3: no controls, no border CZs
es_3 <- feols(es_fml, data = samp_no_border, vcov = ~cz_aewr_region_fe)

# Event study model 4: with controls, no border CZs
es_4 <- feols(es_fml_ctrl, data = samp_no_border, vcov = ~cz_aewr_region_fe)

# Wald test on post-2011 interactions (joint significance)
post_terms <- grep(
  "aewr_cz_p25_l1:yeardummy_201[2-9]|aewr_cz_p25_l1:yeardummy_202",
  names(coef(es_1)),
  value = TRUE
)
wald(es_1, keep = post_terms)
wald(es_2, keep = post_terms)

es_dict <- c(
  "aewr_cz_p25_l1" = "Lagged AEWR vs 25th pct wage gap",
  "yeardummy_2008" = "2008",
  "yeardummy_2009" = "2009",
  "yeardummy_2010" = "2010",
  "yeardummy_2012" = "2012",
  "yeardummy_2013" = "2013",
  "yeardummy_2014" = "2014",
  "yeardummy_2015" = "2015",
  "yeardummy_2016" = "2016",
  "yeardummy_2017" = "2017",
  "yeardummy_2018" = "2018",
  "yeardummy_2019" = "2019",
  "yeardummy_2020" = "2020",
  "yeardummy_2021" = "2021",
  "yeardummy_2022" = "2022"
)

table_2 <- etable(
  es_1,
  es_2,
  es_3,
  es_4,
  tex = TRUE,
  title = "Event Study Coefficients (Base Year = 2011)",
  keep = "%aewr_cz_p25_l1:yeardummy",
  headers = c(
    "No Controls",
    "Controls",
    "No Border, No Controls",
    "No Border, Controls"
  ),
  dict = es_dict,
  signif.code = c("***" = 0.01, "**" = 0.05, "*" = 0.10),
  file = path_tables("table_2_event_study.tex"),
  replace = TRUE
)

## Exhibit 15: Event Study Coefficient Plots -----------------------------------

make_coefplot <- function(model) {
  coef_names <- grep(
    "aewr_cz_p25_l1:yeardummy_",
    names(coef(model)),
    value = TRUE
  )
  ct <- model$coeftable[coef_names, , drop = FALSE]

  years_in_model <- as.integer(sub(".*yeardummy_", "", rownames(ct)))

  all_years <- 2008:2022
  coeff_df <- data.frame(year = all_years) %>%
    mutate(
      beta = ifelse(
        year == 2011,
        0,
        ct[match(paste0("aewr_cz_p25_l1:yeardummy_", year), rownames(ct)), 1]
      ),
      se = ifelse(
        year == 2011,
        0,
        ct[match(paste0("aewr_cz_p25_l1:yeardummy_", year), rownames(ct)), 2]
      )
    ) %>%
    mutate(
      upper_ci = beta + 1.96 * se,
      lower_ci = beta - 1.96 * se
    )

  ggplot(coeff_df, aes(x = year)) +
    geom_hline(yintercept = 0, color = "grey40") +
    geom_vline(xintercept = 2011, linetype = "dashed", color = "grey40") +
    geom_ribbon(
      aes(ymin = lower_ci, ymax = upper_ci),
      alpha = 0.2,
      fill = "steelblue"
    ) +
    geom_line(aes(y = beta), color = "steelblue", lwd = 1.2) +
    geom_point(aes(y = beta), color = "steelblue", size = 2) +
    labs(
      x = "Year",
      y = "Coefficient on Lagged AEWR vs 25th pct wage gap"
    ) +
    theme_clean()
}

p_es_1 <- make_coefplot(es_1)
p_es_2 <- make_coefplot(es_2)
p_es_3 <- make_coefplot(es_3)
p_es_4 <- make_coefplot(es_4)

ggsave(
  p_es_1,
  filename = path_figures("coefplot_dd_no_controls.png"),
  width = 8,
  height = 5,
  device = "png"
)

ggsave(
  p_es_2,
  filename = path_figures("coefplot_dd_controls.png"),
  width = 8,
  height = 5,
  device = "png"
)

ggsave(
  p_es_3,
  filename = path_figures("coefplot_dd_no_border_no_controls.png"),
  width = 8,
  height = 5,
  device = "png"
)

ggsave(
  p_es_4,
  filename = path_figures("coefplot_dd_no_border_controls.png"),
  width = 8,
  height = 5,
  device = "png"
)

