# Generated by code/split_do_r_scripts.py.
# Edit the source Do script or split specification, then regenerate.
# Source: Do/H2A Analysis Figs and Tables.R lines 1-48
# Source SHA256: f039e9b3eb25a0ed3f983e7704aa0473d863be9486c970bf8b0067a9e44222ce

## H2A: Analysis Figures and Tables
## Phil Hoxie
## 1/31/24
ensure_project_dirs()

library(arrow)
library(sf)
library(tidyverse)
library(ggspatial)
library(scales)
library(cowplot)
library(ggthemes)
library(fixest)
library(ggfixest)
library(MatchIt)
library(writexl)

set.seed(12345)

date <- paste0(
  substr(Sys.Date(), 1, 4),
  substr(Sys.Date(), 6, 7),
  substr(Sys.Date(), 9, 10)
)

#### Load and Clean County Shape Files -------------------------------------------
zip_path <- path_raw("county_shapefile", "tl_2020_us_county.zip")
unzip(zip_path, exdir = tempdir())
cnt_shp <- st_read(file.path(tempdir(), "tl_2020_us_county.shp"))

h2a_data_ts <- read_parquet(path_processed("h2a_data_ts.parquet"))
h2a_data <- read_parquet(path_processed("h2a_data.parquet"))
aewr_data_full <- read_parquet(path_processed("aewr_data_full.parquet"))

#### County DDD Design -----------------------------------------------------------

county_df <- read_parquet(path_processed("county_df_analysis_year.parquet"))

names(county_df)

