# Generated by code/split_do_r_scripts.py.
# Shared setup for generated split R modules.

split_current_file <- function() {
  frames <- sys.frames()
  for (idx in rev(seq_along(frames))) {
    ofile <- frames[[idx]]$ofile
    if (!is.null(ofile)) {
      return(normalizePath(ofile, winslash = "/", mustWork = FALSE))
    }
  }

  file_arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(file_arg) > 0) {
    return(normalizePath(sub("^--file=", "", file_arg[[1]]), winslash = "/", mustWork = FALSE))
  }

  normalizePath(getwd(), winslash = "/", mustWork = FALSE)
}

split_dir <- dirname(split_current_file())
source(file.path(split_dir, "paths.R"))
ensure_project_dirs()
options(stringsAsFactors = FALSE)

suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(fredr))
suppressPackageStartupMessages(library(arrow))
suppressPackageStartupMessages(library(tidylog))
suppressPackageStartupMessages(library(sf))
suppressPackageStartupMessages(library(ggspatial))
suppressPackageStartupMessages(library(scales))
suppressPackageStartupMessages(library(cowplot))
suppressPackageStartupMessages(library(ggthemes))
suppressPackageStartupMessages(library(fixest))
suppressPackageStartupMessages(library(ggfixest))
suppressPackageStartupMessages(library(MatchIt))
suppressPackageStartupMessages(library(writexl))

split_analysis_sample <- function(county_df) {
  county_df %>%
    filter(
      any_cropland_2007 == 1,
      county_simple_treatment_groups != "always takers"
    )
}

split_county_map <- function(cnt_shp = NULL) {
  if (is.null(cnt_shp)) {
    zip_path <- path_raw("county_shapefile", "tl_2020_us_county.zip")
    unzip(zip_path, exdir = tempdir())
    cnt_shp <- st_read(file.path(tempdir(), "tl_2020_us_county.shp"))
  }

  county_map <- cnt_shp %>%
    mutate(statefip = as.numeric(STATEFP)) %>%
    filter(statefip <= 56 & statefip != 2 & statefip != 15)

  county_map <- st_simplify(
    county_map,
    preserveTopology = FALSE,
    dTolerance = 1000
  )
  county_map$countyfips <- as.numeric(str_c(
    county_map$STATEFP,
    county_map$COUNTYFP
  ))
  county_map
}

split_load_analysis_inputs <- function(
  env = parent.frame(),
  include_date = FALSE,
  include_shape = FALSE,
  include_county_map = FALSE,
  include_h2a_data_ts = FALSE,
  include_h2a_data = FALSE,
  include_aewr_data_full = FALSE,
  include_county_df = FALSE,
  include_samples = FALSE
) {
  if (include_date) {
    assign(
      "date",
      paste0(
        substr(Sys.Date(), 1, 4),
        substr(Sys.Date(), 6, 7),
        substr(Sys.Date(), 9, 10)
      ),
      envir = env
    )
  }

  if (include_shape || include_county_map) {
    zip_path <- path_raw("county_shapefile", "tl_2020_us_county.zip")
    unzip(zip_path, exdir = tempdir())
    cnt_shp <- st_read(file.path(tempdir(), "tl_2020_us_county.shp"))
    assign("zip_path", zip_path, envir = env)
    assign("cnt_shp", cnt_shp, envir = env)
    if (include_county_map) {
      assign("county_map", split_county_map(cnt_shp), envir = env)
    }
  }

  if (include_h2a_data_ts) {
    assign("h2a_data_ts", read_parquet(path_processed("h2a_data_ts.parquet")), envir = env)
  }
  if (include_h2a_data) {
    assign("h2a_data", read_parquet(path_processed("h2a_data.parquet")), envir = env)
  }
  if (include_aewr_data_full) {
    assign("aewr_data_full", read_parquet(path_processed("aewr_data_full.parquet")), envir = env)
  }
  if (include_county_df || include_samples) {
    county_df <- read_parquet(path_processed("county_df_analysis_year.parquet"))
    assign("county_df", county_df, envir = env)
  } else if (exists("county_df", envir = env, inherits = FALSE)) {
    county_df <- get("county_df", envir = env)
  }

  if (include_samples) {
    samp_base <- split_analysis_sample(county_df)
    assign("samp_base", samp_base, envir = env)
    assign("samp_no_border", samp_base %>% filter(border_cz == 0), envir = env)
  }

  invisible(env)
}

split_prepare_bea_fips_xwalk <- function(full_county_set) {
  bea_fips_xwalk <- read_csv(
    file = path_raw("geographic_crosswalks", "phil", "bea_fips_xwalk.csv")
  )

  county_list <- unique(select(full_county_set, fipscounty, countyname)) %>%
    mutate(indata = 1)

  bea_fips_xwalk <- merge(
    x = bea_fips_xwalk,
    y = county_list,
    by.x = "realfips",
    by.y = "fipscounty",
    all.x = TRUE,
    all.y = FALSE
  )

  bea_fips_xwalk %>%
    filter(county == 1) %>%
    select(realfips, beafips)
}

split_apply_bea_fips_xwalk <- function(data, bea_fips_xwalk) {
  data <- merge(
    x = data,
    y = bea_fips_xwalk,
    by.x = "countyfips",
    by.y = "beafips",
    all.x = TRUE,
    all.y = FALSE
  )

  data %>%
    rename(oldfips = countyfips) %>%
    mutate(countyfips = ifelse(!is.na(realfips), realfips, oldfips)) %>%
    select(-oldfips, -realfips)
}

split_save_aewr_region_ts <- function(aewr_data, y_var, y_label, filename_prefix) {
  for (i in sort(unique(aewr_data$aewr_region_num))) {
    plot <- ggplot(
      data = subset(aewr_data, aewr_region_num == i),
      aes(x = year, y = .data[[y_var]])
    ) +
      geom_line() +
      labs(title = paste0("AEWR Region Number: ", i)) +
      xlab(y_label)

    ggsave(
      filename = path_figures("aewr_ts", paste0(filename_prefix, i, ".png")),
      plot,
      device = "png"
    )
  }
  invisible(NULL)
}
