# Generated by code/split_do_r_scripts.py.
# Edit the source Do script or split specification, then regenerate.
# Source: Do/H2A Clean and Load.R lines 956-1412
# Source SHA256: c44740d380f6ca753b3075096a420fe966d482a96291d6929be13a233e50227f

if (!exists("path_processed", mode = "function")) {
  local({
    split_current_file <- function() {
      frames <- sys.frames()
      for (idx in rev(seq_along(frames))) {
        ofile <- frames[[idx]]$ofile
        if (!is.null(ofile)) {
          return(normalizePath(ofile, winslash = "/", mustWork = FALSE))
        }
      }

      file_arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)
      if (length(file_arg) > 0) {
        return(normalizePath(sub("^--file=", "", file_arg[[1]]), winslash = "/", mustWork = FALSE))
      }

      normalizePath(getwd(), winslash = "/", mustWork = FALSE)
    }

    source(file.path(dirname(split_current_file()), "c00_setup.R"))
  })
}

## BEA Data ---------------------------------------------

full_county_set <- read_parquet(path_int("county_adjacency2010.parquet"))
ppi_data <- read_parquet(path_processed("ppi_2012.parquet"))

# job count data
bea_caemp25n_data <- read_parquet(path_int("bea_CAEMP25N_trim.parquet"))
# save lines: 10 50 70 80 90

bea_caemp25n_data <- bea_caemp25n_data %>%
  filter(
    LineCode == 10 |
      LineCode == 50 |
      LineCode == 70 |
      LineCode == 80 |
      LineCode == 90
  )

bea_caemp25n_data <- bea_caemp25n_data %>%
  mutate(
    countyfips = split_fips5(GeoFIPS), # remove quotes
    category = ifelse(
      LineCode == 10,
      "emp_tot",
      ifelse(
        LineCode == 50,
        "emp_farm_propr", # farm proprietors
        ifelse(
          LineCode == 70,
          "emp_farm",
          ifelse(
            LineCode == 80,
            "emp_nonfarm",
            ifelse(LineCode == 90, "emp_privatenonfarm", NA)
          )
        )
      )
    )
  )

bea_caemp25n_data <- bea_caemp25n_data %>%
  select(9:32)

bea_caemp25n_data <- bea_caemp25n_data %>% # wow, that was easy
  pivot_longer(
    cols = starts_with("y"),
    names_to = "year",
    names_prefix = "y",
    values_to = "temp",
    values_drop_na = F
  )

bea_caemp25n_data <- bea_caemp25n_data %>%
  mutate(emp = as.numeric(temp)) %>%
  select(-temp)

# put into year - county rows, so, pivot again

bea_caemp25n_data <- bea_caemp25n_data %>% # wow, that was easy
  pivot_wider(names_from = "category", values_from = "emp")

bea_caemp25n_data %>%
  group_by(year) %>%
  tally()

bea_caemp25n_data <- bea_caemp25n_data %>%
  filter(year > 2007 & year <= 2022)

# fix fips
# from: https://www.economy.com/support/blog/getfile.asp?did=869A03D1-5D74-4376-A606-00A8C64DDB0B&fid=a18d6d4873834f749d42ded633850a5e.xlsx

bea_fips_xwalk <- split_prepare_bea_fips_xwalk(full_county_set)

bea_caemp25n_data <- split_apply_bea_fips_xwalk(bea_caemp25n_data, bea_fips_xwalk)

# SD Oglala Lakota to Shannon
bea_caemp25n_data <- bea_caemp25n_data %>%
  mutate(
    countyfips = case_when(
      countyfips == "46102" ~ "46113",
      .default = countyfips
    )
  )

head(bea_caemp25n_data)

write_parquet(
  bea_caemp25n_data,
  path_processed("bea_caemp25n_data_year.parquet")
)
cat(
  "bea_caemp25n_data_year:",
  nrow(bea_caemp25n_data),
  "rows,",
  ncol(bea_caemp25n_data),
  "cols\n"
)

# farm finance
bea_cainc45_data <- read_parquet(path_int("bea_CAINC45_trim.parquet"))
# save lines: 20 60 130 210 270 150

bea_cainc45_data <- bea_cainc45_data %>%
  filter(
    LineCode == 20 |
      LineCode == 60 |
      LineCode == 130 |
      LineCode == 210 |
      LineCode == 270 |
      LineCode == 150
  )

bea_cainc45_data <- bea_cainc45_data %>%
  mutate(
    countyfips = split_fips5(GeoFIPS), # remove quotes
    category = ifelse(
      LineCode == 60,
      "farm_cashcrops", # Cash receipts: Crops
      ifelse(
        LineCode == 20,
        "farm_cashanimal", #  Cash receipts: Livestock and products
        ifelse(
          LineCode == 130,
          "farm_govpayments", # Government payments
          ifelse(
            LineCode == 210,
            "farm_laborexpense", # Hired farm labor expenses
            ifelse(
              LineCode == 270,
              "farm_cashandinc", # cash receipts and other income
              ifelse(LineCode == 150, "farm_prodexp", NA)
            )
          )
        )
      )
    )
  ) # Production expenses

bea_cainc45_data %>%
  group_by(category) %>%
  tally()

names(bea_cainc45_data)

bea_cainc45_data <- bea_cainc45_data %>%
  select(43:64) # be careful, this gets to be really a lot of data.

names(bea_cainc45_data)

bea_cainc45_data <- bea_cainc45_data %>% # wow, that was easy
  pivot_longer(
    cols = starts_with("y"),
    names_to = "year",
    names_prefix = "y",
    values_to = "temp",
    values_drop_na = T
  )

bea_cainc45_data <- bea_cainc45_data %>%
  mutate(fin = as.numeric(temp)) %>%
  select(-temp)

# put into year - county rows, so, pivot again

bea_cainc45_data <- bea_cainc45_data %>% # wow, that was easy
  pivot_wider(names_from = "category", values_from = "fin")

# real

bea_cainc45_data <- merge(
  bea_cainc45_data,
  ppi_data,
  by = "year",
  all.x = T,
  all.y = F
)

bea_cainc45_data <- bea_cainc45_data %>%
  mutate(
    farm_cashanimal_ppi = farm_cashanimal / ppi_2012,
    farm_cashcrops_ppi = farm_cashcrops / ppi_2012,
    farm_govpayments_ppi = farm_govpayments / ppi_2012,
    farm_prodexp_ppi = farm_prodexp / ppi_2012,
    farm_laborexpense_ppi = farm_laborexpense / ppi_2012,
    farm_cashandinc_ppi = farm_cashandinc / ppi_2012
  )

bea_cainc45_data %>%
  group_by(year) %>%
  tally()

names(bea_cainc45_data)

bea_cainc45_data <- bea_cainc45_data %>%
  filter(year > 2007 & year <= 2022)

bea_cainc45_data <- split_apply_bea_fips_xwalk(bea_cainc45_data, bea_fips_xwalk)

write_parquet(
  bea_cainc45_data,
  path_processed("bea_cainc45_data_year.parquet")
)
cat(
  "bea_cainc45_data_year:",
  nrow(bea_cainc45_data),
  "rows,",
  ncol(bea_cainc45_data),
  "cols\n"
)


## County Pop estimates ---------------------------------
# documentation: https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2000-2009/co-est2009-alldata.pdf

census_pop_2000 <- read_csv(
  path_raw("census_population_estimates", "co-est2009-alldata.csv")
)
census_pop_2010 <- read_csv(
  path_raw("census_population_estimates", "co-est2019-alldata.csv")
)
census_pop_2020 <- read_csv(
  path_raw("census_population_estimates", "co-est2022-alldata.csv")
)

ct_xwalk <- read_csv(
  path_raw("geographic_crosswalks", "phil", "ct_region_xwalk.csv")
)
ct_popgrth <- read_csv(
  path_raw("geographic_crosswalks", "phil", "ct_pop_grth.csv")
)

census_pop_2000 <- census_pop_2000 %>%
  filter(as.integer(SUMLEV) == 50) %>%
  select(STATE, COUNTY, 10:19)
census_pop_2010 <- census_pop_2010 %>%
  filter(as.integer(SUMLEV) == 50) %>%
  select(STATE, COUNTY, 10:19)
census_pop_2020 <- census_pop_2020 %>%
  filter(as.integer(SUMLEV) == 50) %>%
  select(STATE, COUNTY, 9:11)

head(census_pop_2000)
head(census_pop_2010)
head(census_pop_2020)

# fix CT county to region nonsense.
# https://www.ctdata.org/blog/geographic-resources-for-connecticuts-new-county-equivalent-geography
# project using state growth rates

census_pop_ests <- merge(
  x = census_pop_2000,
  y = census_pop_2010,
  by = c("STATE", "COUNTY"),
  all = T
)
census_pop_ests <- merge(
  x = census_pop_ests,
  y = census_pop_2020,
  by = c("STATE", "COUNTY"),
  all = T
)

rm(census_pop_2000, census_pop_2010, census_pop_2020)

census_pop_ests <- census_pop_ests %>%
  mutate(
    countyfips = split_countyfips(STATE, COUNTY)
  )

census_pop_ests <- census_pop_ests %>%
  select(-STATE, -COUNTY)

census_pop_ests <- census_pop_ests %>%
  pivot_longer(
    cols = starts_with("POPESTIMATE"),
    names_to = "year",
    names_prefix = "POPESTIMATE",
    values_to = "pop_census",
    values_drop_na = F
  )

census_pop_ests %>%
  group_by(year) %>%
  tally()

census_pop_ests <- census_pop_ests %>%
  filter(year > 2007 & year <= 2022)

head(census_pop_ests)

# fix CT

census_pop_ests <- census_pop_ests %>%
  mutate(
    ct_region = ifelse(
      as.integer(countyfips) >= 9000 & as.integer(countyfips) <= 9999 & year >= 2020,
      1,
      0
    )
  ) # remove CT in 2020 on

ct_base <- census_pop_ests %>%
  filter(as.integer(countyfips) >= 9000 & as.integer(countyfips) <= 9999 & year == 2019)

census_pop_ests <- census_pop_ests %>%
  filter(ct_region == 0) %>%
  select(-ct_region)

census_pop_ests <- census_pop_ests %>%
  filter(as.integer(countyfips) < 9100 | as.integer(countyfips) > 9199) # get rid of the regions

ct_base <- ct_base %>%
  filter(as.integer(countyfips) < 9100) %>%
  select(countyfips, pop_census) %>%
  mutate(
    pop_census2020 = pop_census * ct_popgrth$grt[ct_popgrth$year == 2020],
    pop_census2021 = pop_census2020 * ct_popgrth$grt[ct_popgrth$year == 2021],
    pop_census2022 = pop_census2021 * ct_popgrth$grt[ct_popgrth$year == 2022]
  )

ct_base <- ct_base %>%
  select(-pop_census)

ct_fill <- ct_base %>%
  pivot_longer(
    cols = starts_with("pop_census"),
    names_to = "year",
    names_prefix = "pop_census",
    values_to = "pop_census",
    values_drop_na = F
  )


census_pop_ests <- rbind(census_pop_ests, ct_fill)

# fix SD county change

census_pop_ests$countyfips <- replace(
  census_pop_ests$countyfips,
  census_pop_ests$countyfips == "46102",
  "46113"
)

census_pop_ests %>% filter(countyfips == "46111") %>% tally() # double

census_pop_ests <- census_pop_ests %>%
  filter(!is.na(pop_census))

census_pop_ests %>% filter(countyfips == "46111") %>% tally() # fixed


write_parquet(
  census_pop_ests,
  path_processed("census_pop_ests_year.parquet")
)
cat(
  "census_pop_ests_year:",
  nrow(census_pop_ests),
  "rows,",
  ncol(census_pop_ests),
  "cols\n"
)

## all county sample ----------------------------------------------------------

head(full_county_set)

county_list_unique <- unique(select(full_county_set, fipscounty, countyname))

dim(county_list_unique)

years <- seq(2008, 2022)
county_df <- NULL

for (i in 1:length(years)) {
  temp <- county_list_unique %>%
    mutate(year = years[i])
  county_df <- bind_rows(county_df, temp)
  rm(temp)
}

head(county_df)

county_df %>%
  group_by(year) %>%
  tally()

write_parquet(county_df, path_processed("county_df_year.parquet"))
cat("county_df_year:", nrow(county_df), "rows,", ncol(county_df), "cols\n")

# remove files -------------------

str_detect(ls(), "folder_")

objects <- data.frame(name = ls(), keep = str_detect(ls(), "folder_")) %>%
  filter(keep == F)

rm(list = objects[, 1])
gc()
