# Generated by code/split_do_r_scripts.py.
# Edit the source Do script or split specification, then regenerate.
# Source: Do/H2A Analysis Figs and Tables.R lines 1668-1961
# Source SHA256: 337e790bd6e243d9463d6f4557b803f9a56cbaf8985ad5ca53083b1925b0987c

if (!exists("path_processed", mode = "function")) {
  local({
    split_current_file <- function() {
      frames <- sys.frames()
      for (idx in rev(seq_along(frames))) {
        ofile <- frames[[idx]]$ofile
        if (!is.null(ofile)) {
          return(normalizePath(ofile, winslash = "/", mustWork = FALSE))
        }
      }

      file_arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)
      if (length(file_arg) > 0) {
        return(normalizePath(sub("^--file=", "", file_arg[[1]]), winslash = "/", mustWork = FALSE))
      }

      normalizePath(getwd(), winslash = "/", mustWork = FALSE)
    }

    source(file.path(dirname(split_current_file()), "c00_setup.R"))
  })
}

## Exhibit 16: Summary Statistics Table -----------------------------------------

split_load_analysis_inputs(
  include_county_df = TRUE,
  include_samples = TRUE,
  include_county_map = TRUE
)

sumstats_vars <- list(
  "H-2A share of 2011 farm employment" = "h2a_cert_share_farm_workers_2011_start_year",
  "H-2A certified workers (start year)" = "nbr_workers_certified_start_year",
  "Farm employment 2011 (baseline)" = "emp_farm_2011",
  "AEWR p25 bite (2012 $)" = "aewr_cz_p25",
  "Log population" = "ln_pop_census",
  "Employment-to-population ratio" = "emp_pop_ratio"
)

sumstats_rows <- purrr::imap_dfr(sumstats_vars, function(col, label) {
  x <- samp_base[[col]]
  tibble(
    Variable = label,
    N = sum(!is.na(x)),
    Mean = mean(x, na.rm = TRUE),
    SD = sd(x, na.rm = TRUE),
    Min = min(x, na.rm = TRUE),
    Max = max(x, na.rm = TRUE)
  )
})

sumstats_tex <- c(
  "\\begin{table}[htbp]",
  "\\centering",
  "\\caption{Summary Statistics: Difference-in-Differences Variables}",
  "\\label{tab:sumstats}",
  "\\begin{tabular}{lrrrrr}",
  "\\hline\\hline",
  "Variable & N & Mean & SD & Min & Max \\\\",
  "\\hline",
  apply(sumstats_rows, 1, function(r) {
    sprintf(
      "%s & %s & %.3f & %.3f & %.3f & %.3f \\\\",
      r["Variable"],
      format(as.integer(r["N"]), big.mark = ","),
      as.numeric(r["Mean"]),
      as.numeric(r["SD"]),
      as.numeric(r["Min"]),
      as.numeric(r["Max"])
    )
  }),
  "\\hline\\hline",
  "\\end{tabular}",
  "\\end{table}"
)

writeLines(
  sumstats_tex,
  con = path_tables("table_sumstats_dd_variables.tex")
)

#### Exhibit 17: Fisher Price Index Time Series -----------------------------------

fisher_ts <- samp_base %>%
  filter(!is.na(fisher_index_ppi)) %>%
  group_by(year) %>%
  summarise(
    mean_price = mean(fisher_index_ppi, na.rm = TRUE),
    sd_price = sd(fisher_index_ppi, na.rm = TRUE)
  )

ts_fisher_price <- ggplot(fisher_ts, aes(x = year, y = mean_price)) +
  geom_ribbon(
    aes(ymin = mean_price - sd_price, ymax = mean_price + sd_price),
    alpha = 0.2,
    fill = "steelblue"
  ) +
  geom_line(linewidth = 1.25, color = "#2166ac") +
  geom_vline(xintercept = 2011, linetype = "dashed") +
  scale_x_continuous(breaks = seq(2008, 2022, by = 2)) +
  labs(
    x = "Year",
    y = "Fisher Price Index (real, 2012=100)",
    title = "Agricultural Price Index Across Counties, 2008–2022",
    subtitle = "Mean ± 1 SD across sample counties"
  ) +
  theme_clean()

ts_fisher_price

ggsave(
  filename = path_figures("ts_fisher_price_index_ppi.png"),
  ts_fisher_price,
  device = "png"
)

#### Exhibit 18: DD Regressions — Fisher Price Index as Outcome ------------------

price_dd_1 <- feols(
  fisher_index_ppi ~
    aewr_cz_p25_l1 * postdummy | county_fe + year_fe,
  data = samp_base,
  vcov = ~cz_aewr_region_fe
)

price_dd_2 <- feols(
  fisher_index_ppi ~
    aewr_cz_p25_l1 *
    postdummy +
    ln_pop_census +
    emp_pop_ratio |
    county_fe + year_fe,
  data = samp_base,
  vcov = ~cz_aewr_region_fe
)

price_dd_3 <- feols(
  fisher_index_ppi ~
    aewr_cz_p25_l1 * postdummy | county_fe + year_fe,
  data = samp_no_border,
  vcov = ~cz_aewr_region_fe
)

price_dd_4 <- feols(
  fisher_index_ppi ~
    aewr_cz_p25_l1 *
    postdummy +
    ln_pop_census +
    emp_pop_ratio |
    county_fe + year_fe,
  data = samp_no_border,
  vcov = ~cz_aewr_region_fe
)

table_fisher_price <- etable(
  price_dd_1,
  price_dd_2,
  price_dd_3,
  price_dd_4,
  tex = TRUE,
  title = "The Effect of the AEWR Wage Premium on Agricultural Prices",
  headers = c(
    "No Controls",
    "Controls",
    "No Border, No Controls",
    "No Border, Controls"
  ),
  dict = c(
    "fisher_index_ppi" = "Fisher price index (real, 2012=100)",
    "aewr_cz_p25_l1" = "Lagged AEWR vs 25th pct wage gap",
    "postdummy" = "Post",
    "ln_pop_census" = "Log population",
    "emp_pop_ratio" = "Employment-to-pop ratio"
  ),
  signif.code = c("***" = 0.01, "**" = 0.05, "*" = 0.10),
  file = path_tables("table_fisher_price_dd.tex"),
  replace = TRUE
)

#### Exhibit 19: County Map — Fisher Price Index Ratio 2022 / 2008 ---------------

fisher_map_data <- samp_base %>%
  filter(year %in% c(2011, 2022), !is.na(fisher_index_ppi)) %>%
  select(countyfips, year, fisher_index_ppi) %>%
  distinct(countyfips, year, .keep_all = TRUE) %>%
  pivot_wider(
    id_cols = countyfips,
    names_from = year,
    values_from = fisher_index_ppi,
    names_prefix = "price_"
  ) %>%
  mutate(price_ratio_2022_2011 = price_2022 / price_2011) %>%
  filter(!is.na(price_ratio_2022_2011))

ratio_median <- median(fisher_map_data$price_ratio_2022_2011, na.rm = TRUE)

fisher_county_map <- merge(
  x = county_map,
  y = fisher_map_data,
  by = "countyfips",
  all.x = TRUE,
  all.y = FALSE
)

map_fisher_price_ratio <- ggplot(fisher_county_map) +
  geom_sf(
    aes(fill = price_ratio_2022_2011),
    color = alpha("grey", 0.3),
    linewidth = 0.1
  ) +
  theme(
    panel.grid.major = element_line(
      color = gray(0.5),
      linetype = "dashed",
      linewidth = 0.5
    ),
    panel.background = element_rect(fill = "aliceblue")
  ) +
  theme_bw() +
  annotation_north_arrow(
    location = "bl",
    which_north = "true",
    pad_x = unit(0.05, "in"),
    pad_y = unit(0.25, "in"),
    style = north_arrow_fancy_orienteering
  ) +
  annotation_scale(location = "bl", width_hint = 0.4) +
  scale_fill_gradient2(
    low = muted("#2166ac"),
    mid = "white",
    midpoint = ratio_median,
    high = muted("#b2182b"),
    name = "Price Index\nRatio\n2022 / 2011",
    na.value = "grey90"
  )

map_fisher_price_ratio

ggsave(
  filename = path_figures("map_fisher_price_ratio_2022_2011.png"),
  map_fisher_price_ratio,
  device = "png"
)

#### Exhibit 20: Fisher Price Index Investigation — Labor Share DD --------------
# Fisher price index (fisher_index_ppi) construction:
#   Script: code/b02_01_price_index_nass_synthetic_cdl.py
#   Inputs: CDL county-crop acreage (croplandcros_county_crop_acres.parquet)
#   with NASS synthetic prices/yields per crop (state, then national fallback)
#   Method: chained bilateral Fisher — geometric mean of Laspeyres and Paasche,
#           matched set = crops present in both consecutive years (inner join).
#           Base year 2011 = 100. Forward chain 2012-2022; backward 2010-2008.
#   Deflation: fisher_index_ppi = fisher_index / ppi_2012 [Build Dataset L1700]
#
# Quantity/composition proxy available in county_df:
#   share_farm_laborexp_prodexp = farm_laborexpense / farm_prodexp (BEA CAINC45)
#   This is a genuine share [0,1]. If AEWR increases shift production toward less
#   labor-intensive crops (substitution away from H-2A-intensive crops), this
#   share should fall. CDL crop-level acreage shares are NOT in county_df
#   (only any_cropland_2007); could be added from cdl_cropshares.parquet.

laborshare_dd_1 <- feols(
  share_farm_laborexp_prodexp ~
    aewr_cz_p25_l1 * postdummy | county_fe + year_fe,
  data = samp_base,
  vcov = ~cz_aewr_region_fe
)

laborshare_dd_2 <- feols(
  share_farm_laborexp_prodexp ~
    aewr_cz_p25_l1 *
    postdummy +
    ln_pop_census +
    emp_pop_ratio |
    county_fe + year_fe,
  data = samp_base,
  vcov = ~cz_aewr_region_fe
)

laborshare_dd_3 <- feols(
  share_farm_laborexp_prodexp ~
    aewr_cz_p25_l1 * postdummy | county_fe + year_fe,
  data = samp_no_border,
  vcov = ~cz_aewr_region_fe
)

laborshare_dd_4 <- feols(
  share_farm_laborexp_prodexp ~
    aewr_cz_p25_l1 *
    postdummy +
    ln_pop_census +
    emp_pop_ratio |
    county_fe + year_fe,
  data = samp_no_border,
  vcov = ~cz_aewr_region_fe
)

etable(
  laborshare_dd_1,
  laborshare_dd_2,
  laborshare_dd_3,
  laborshare_dd_4,
  tex = TRUE,
  title = "The Effect of the AEWR Wage Premium on Farm Labor Share of Production Expense",
  headers = c(
    "No Controls",
    "Controls",
    "No Border, No Controls",
    "No Border, Controls"
  ),
  dict = c(
    "share_farm_laborexp_prodexp" = "Labor share of farm production expense",
    "aewr_cz_p25_l1" = "Lagged AEWR vs 25th pct wage gap",
    "postdummy" = "Post",
    "ln_pop_census" = "Log population",
    "emp_pop_ratio" = "Employment-to-pop ratio"
  ),
  signif.code = c("***" = 0.01, "**" = 0.05, "*" = 0.10),
  file = path_tables("table_laborshare_dd.tex"),
  replace = TRUE
)

